// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: f408c30f03e97af6145cdb7bc857329a19155a26060adf677829c5dc33ff23d0
export const codeExecutionEnvRequirement = {"options":[["VERCEL_OIDC_TOKEN"],["VERCEL_TEAM_ID","VERCEL_PROJECT_ID","VERCEL_TOKEN"]],"description":"VERCEL_OIDC_TOKEN or VERCEL_TEAM_ID + VERCEL_PROJECT_ID + VERCEL_TOKEN"};
