// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 0beccc826aee3ee28ee8b366777687191427155da69599288c7d8cef62efa36d
import type { CodeExecutor } from "@/lib/eve/code-executor";
import { executeCode as execute } from "./vercel-code-execution/tool";

export const codeExecutor: CodeExecutor | undefined = execute;
