// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 9b0395cc57741a92cdb2fcc4cdfb05de87b7d936090a59e92d1821a1314833e3
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import type { CodeExecutor } from "@/lib/eve/code-executor";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { executeCode as execute } from "./vercel-code-execution/tool";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports, no-undefined -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const codeExecutor: CodeExecutor | undefined = execute;
