// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 6f6a0681df79c19ab8f959829e2bdc70b99ddcc61d8ce6d9f3aa0969d11e2972
export const codeExecutionEnvRequirement = {"allOf":[{"description":"Vercel OIDC or team/project/token credentials","options":[["VERCEL_OIDC_TOKEN"],["VERCEL_TEAM_ID","VERCEL_PROJECT_ID","VERCEL_TOKEN"]],"runtimeAuth":"vercel-oidc"}],"description":"VERCEL_OIDC_TOKEN or VERCEL_TEAM_ID + VERCEL_PROJECT_ID + VERCEL_TOKEN","options":[["VERCEL_OIDC_TOKEN"],["VERCEL_TEAM_ID","VERCEL_PROJECT_ID","VERCEL_TOKEN"]]};
export const supportsSavedDocuments = true;
