// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 35236bf2ebab9c564840c0d3d4d9d32102017e72c55f2b0f94a9917b7c834d37
import type { CodeExecutor } from "@/lib/eve/code-executor";
import { executeCode as execute } from "./vercel-code-execution/tool";

// oxlint-disable-next-line no-undefined -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export const codeExecutor: CodeExecutor | undefined = execute;
