// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 2b86f907b4a3bc336f89fa201a456e65cd28539797db1c73c795b9e3dd69ebd3
import type { CodeExecutionToolFactory } from "@/tools/platform/code-execution-contract";
import { createCodeExecution as selectedFactory } from "./vercel-code-execution/tool";
const selected: CodeExecutionToolFactory = selectedFactory;
export { selected as createCodeExecution };
