// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 804f633cc6438dbec128161b3efd3dafcbe119dfdc7d714bdd954fa8d942ad25
export const codeExecutionEnvRequirement = {"description":"VERCEL_OIDC_TOKEN or VERCEL_TEAM_ID + VERCEL_PROJECT_ID + VERCEL_TOKEN","options":[["VERCEL_OIDC_TOKEN"],["VERCEL_TEAM_ID","VERCEL_PROJECT_ID","VERCEL_TOKEN"]]};
