// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 50114e77c67fda35d3ba188136acceb768843a4a6a2d0edc2023714121d23da0
import type { LucideIcon } from "lucide-react";
import { Edit3 as Icon0, Edit3 as Icon1, Edit3 as Icon2, Telescope as Icon3, Edit3 as Icon4, Edit3 as Icon5, Edit3 as Icon6, Images as Icon7, Video as Icon8, GlobeIcon as Icon9 } from "lucide-react";

export const composerTools: Readonly<Record<string, { icon: LucideIcon; name: string; shortName: string } | undefined>> = {
  "createCodeDocument": { icon: Icon0, name: "Canvas", shortName: "Canvas" },
  "createSheetDocument": { icon: Icon1, name: "Canvas", shortName: "Canvas" },
  "createTextDocument": { icon: Icon2, name: "Canvas", shortName: "Canvas" },
  "deepResearch": { icon: Icon3, name: "Deep Research", shortName: "Research" },
  "editCodeDocument": { icon: Icon4, name: "Canvas", shortName: "Canvas" },
  "editSheetDocument": { icon: Icon5, name: "Canvas", shortName: "Canvas" },
  "editTextDocument": { icon: Icon6, name: "Canvas", shortName: "Canvas" },
  "generateImage": { icon: Icon7, name: "Create an image", shortName: "Image" },
  "generateVideo": { icon: Icon8, name: "Create a video", shortName: "Video" },
  "webSearch": { icon: Icon9, name: "Web Search", shortName: "Search" },
};
