// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 45c44c20f07944d3bcee4ddb6ce18402b3ea0f7fae303b100b5c277d6896323a
import { Edit3 as Icon0, Edit3 as Icon1, Edit3 as Icon2, Telescope as Icon3, Edit3 as Icon4, Edit3 as Icon5, Edit3 as Icon6, Images as Icon7, Video as Icon8, Globe as Icon9 } from "lucide-react";
import type { LucideIcon } from "lucide-react";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export const composerTools: Readonly<Record<string, { icon: LucideIcon; name: string; shortName: string } | undefined>> = {
  "createCodeDocument": { icon: Icon0, name: "Canvas", shortName: "Canvas" },
  "createSheetDocument": { icon: Icon1, name: "Canvas", shortName: "Canvas" },
  "createTextDocument": { icon: Icon2, name: "Canvas", shortName: "Canvas" },
  "deepResearch": { icon: Icon3, name: "Deep Research", shortName: "Research" },
  "editCodeDocument": { icon: Icon4, name: "Canvas", shortName: "Canvas" },
  "editSheetDocument": { icon: Icon5, name: "Canvas", shortName: "Canvas" },
  "editTextDocument": { icon: Icon6, name: "Canvas", shortName: "Canvas" },
  "generateImage": { icon: Icon7, name: "Create an image", shortName: "Image" },
  "generateVideo": { icon: Icon8, name: "Create a video", shortName: "Video" },
  "webSearch": { icon: Icon9, name: "Web Search", shortName: "Search" },
};
