// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 346fe3bd8e90d42a534459a07eb49089e026b83559c639276e00e25e07199fa6
"use client";

import type { DocumentUiRegistry } from "@/lib/eve/document-ui";

import { documentUi as document0 } from "./code-documents/document";
import { documentUi as document1 } from "./sheet-documents/document";
import { documentUi as document2 } from "./text-documents/document";

export const documentUi: DocumentUiRegistry = {
  code: document0,
  sheet: document1,
  text: document2,
};
