// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 72d4cbdd152e051f124915528f73fad22966d6bb6ab4a3fa316d0bb809f0a57f
"use client";

// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import type { DocumentUiRegistry } from "@/lib/eve/document-ui";

// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { documentUi as document0 } from "./code-documents/document";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { documentUi as document1 } from "./sheet-documents/document";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { documentUi as document2 } from "./text-documents/document";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const documentUi: DocumentUiRegistry = {
  code: document0,
  sheet: document1,
  text: document2,
};
