// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 072f3433f960f98289eb119569ed5aa99598f24b3eacf27c3ab57a5163e8c452
"use client";

import type { DocumentUiRegistry } from "@/lib/eve/document-ui";

import { documentUi as document0 } from "./code-documents/document";
import { documentUi as document1 } from "./sheet-documents/document";
import { documentUi as document2 } from "./text-documents/document";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export const documentUi: DocumentUiRegistry = {
  code: document0,
  sheet: document1,
  text: document2,
};
