// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 2f90a86c5da2f047920369a78e30ae203e3ff02dcb96f9ef9d5d5d9577e7f3ab
"use client";

import type { ComponentType } from "react";

import type { DocumentRunProps } from "@/lib/eve/document-ui";

import { EveDocumentRun as InstalledDocumentRun } from "./saved-code-execution/document";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export const DocumentRun: ComponentType<DocumentRunProps> | undefined =
  InstalledDocumentRun;
