// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 1d69c2e95526ac94a051fa111b0f337614c03bc73f64d2e87c4e289dd5023cbc
"use client";

import type { ComponentType } from "react";

import type { DocumentRunProps } from "@/lib/eve/document-ui";

import { EveDocumentRun as InstalledDocumentRun } from "./saved-code-execution/document";

// oxlint-disable-next-line no-undefined -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export const DocumentRun: ComponentType<DocumentRunProps> | undefined =
  InstalledDocumentRun;
