// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: ee2f91f3c56feba2798d8c8e83e4539d894f96a19fba3a0fb8f6cf0307e1ed11
"use client";

import type { ComponentType } from "react";

import type { DocumentRunProps } from "@/lib/eve/document-ui";

import { EveDocumentRun as InstalledDocumentRun } from "./saved-code-execution/document";

export const DocumentRun: ComponentType<DocumentRunProps> | undefined =
  InstalledDocumentRun;
