// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 9c02fd84c7ce809f953ff94ed68dd707fe9974fa6aa5ffa334c1c6f2d7ec3159
export const imageGenerationEnvRequirement = {"options":[[]],"description":""};
