// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: c3ad6f747277b84d0fd5225d073befb69a25e8aaf22e783881dc64262fedfb6d
// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const installedToolNames: ReadonlySet<string> = new Set(["createCodeDocument","editCodeDocument","deepResearch","deleteDocument","generateImage","generateVideo","getWeather","readDocument","retrieveUrl","runCodeDocument","createSheetDocument","editSheetDocument","webSearch","createTextDocument","editTextDocument","codeExecution","wordCount"]);
// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const installedDocumentKinds: ReadonlySet<string> = new Set([
  "code",
  "sheet",
  "text",
]);
