// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 708203d907d8609476dd4f690ccc608ff80523e1aecdf9e6490b1011a0112a0e
export const installedDocumentKinds: ReadonlySet<string> = new Set([
  "code",
  "sheet",
  "text",
]);
