// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 84b5fa88e221e7f070f2a9cb79c8c9aa0842935d9b562778456cba9c6f3e9a2d
const installedToolNames: ReadonlySet<string> = new Set(["createCodeDocument","editCodeDocument","deepResearch","deleteDocument","generateImage","generateVideo","getWeather","readDocument","retrieveUrl","runCodeDocument","createSheetDocument","editSheetDocument","webSearch","createTextDocument","editTextDocument","codeExecution","wordCount"]);
const installedDocumentKinds: ReadonlySet<string> = new Set([
  "code",
  "sheet",
  "text",
]);
// oxlint-disable-next-line import/no-named-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export { installedToolNames, installedDocumentKinds };
