// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 74b9fedd71e9222243601094b3ad01852b8b6ca76ae4828739becf2cdac77d8e
import { defineToolSet } from "@/lib/eve/tool-types";
import { generateImageTool as tool0 } from "./generate-image/tool";
import { generateVideoTool as tool1 } from "./generate-video/tool";
import { retrieveUrl as tool2 } from "./retrieve-url/tool";
import { webSearch as tool3 } from "./tavily-search/tool";
import { codeExecution as tool4 } from "./vercel-code-execution/tool";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export const providers = defineToolSet({
  codeExecution: tool4,
  generateImage: tool0,
  generateVideo: tool1,
  retrieveUrl: tool2,
  webSearch: tool3,
});
