// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: a03137d86c0e7ce4e5bc322e95ed25c4fdca85baf27297184a83ce656c428642
import { defineToolSet } from "@/lib/eve/tool-types";
import { generateImageTool as tool0 } from "./generate-image/tool";
import { generateVideoTool as tool1 } from "./generate-video/tool";
import { retrieveUrl as tool2 } from "./retrieve-url/tool";
import { webSearch as tool3 } from "./tavily-search/tool";
import { codeExecution as tool4 } from "./vercel-code-execution/tool";

export const providers = defineToolSet({
  codeExecution: tool4,
  generateImage: tool0,
  generateVideo: tool1,
  retrieveUrl: tool2,
  webSearch: tool3,
});
