// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: a5f2224619b27caee8eb820c262922b8797d19c9b0ade55bd2edd078dc4adcdc
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { defineToolSet } from "@/lib/eve/tool-types";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { generateImageTool as tool0 } from "./generate-image/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { generateVideoTool as tool1 } from "./generate-video/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { retrieveUrl as tool2 } from "./retrieve-url/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { webSearch as tool3 } from "./tavily-search/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { codeExecution as tool4 } from "./vercel-code-execution/tool";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const providers = defineToolSet({
  codeExecution: tool4,
  generateImage: tool0,
  generateVideo: tool1,
  retrieveUrl: tool2,
  webSearch: tool3,
});
