// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 1a4bdeaf988c3fd1522b67e6727c9fb92110f4c2ef9b861c268fcf2a8efecb45
import type { SearchToolFactory } from "@/tools/platform/search-presentation";
import { createWebSearch as selectedFactory } from "./tavily-search/tool";
const selected: SearchToolFactory = selectedFactory;
export { selected as createWebSearch };
