// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 009fc29fa2e4494779012b6f4c6f2b2c3537eabdc23e2ac35cd2da2099b1bef2
export const searchEnvRequirement = {"options":[["TAVILY_API_KEY"]],"description":"TAVILY_API_KEY"};
