// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: b651474d5540881ffcd6ed7437119d55bad6f79b0fb6a3d73a819d9170ab1748
import type { SearchToolFactory } from "@/tools/platform/search-presentation";
import { createWebSearch } from "./tavily-search/tool";
const selectedSearch = createWebSearch satisfies SearchToolFactory;
export { selectedSearch as createWebSearch };
