// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 2aa263ff55da0995e88cf4f0e2e5b6418c65591990332595ad00ac209445f6bb
import type { ToolSet } from "ai";
import { customTools } from "./custom-tools";
import { generateImageTool as tool0 } from "./generate-image/tool";
import { getWeather as tool1 } from "./get-weather/tool";
import { retrieveUrl as tool2 } from "./retrieve-url/tool";
import { webSearch as tool3 } from "./tavily-search/tool";
import { codeExecution as tool4 } from "./vercel-code-execution/tool";
import { wordCount as tool5 } from "./word-count/tool";

const installed = {
  generateImage: tool0,
  getWeather: tool1,
  retrieveUrl: tool2,
  webSearch: tool3,
  codeExecution: tool4,
  wordCount: tool5,
} satisfies ToolSet;
for (const key of Object.keys(customTools)) {
  if (Object.hasOwn(installed, key)) {
    throw new Error(`Duplicate tool registration: ${key}`);
  }
}
export const tools = { ...installed, ...customTools };
