// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 8a4d85d1bc0db910d5711d74f224f9aa2c1c0a7551a266f9e89fdc0c356967ca
import type { ToolAvailability } from "@/lib/eve/tool-availability";
import { researchAvailable as available0 } from "./deep-research/availability";

export const toolAvailability: Record<string, ToolAvailability> = {
  deepResearch: available0,
};
