// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 56272793369bc4083bcadb8a14cbb53781df5b25668e8e4712662b0980a692ba
/* oxlint-disable import/max-dependencies -- This generated registry enumerates every installed tool; its dependencies grow with the user-selected installation. */
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { defineToolSet } from "@/lib/eve/tool-types";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { customTools } from "./custom-tools";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { providers } from "./providers";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import {
  createCodeDocument as tool0,
  editCodeDocument as tool1,
} from "./code-documents/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { deleteDocument as tool3 } from "./delete-document/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { getWeather as tool6 } from "./get-weather/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { readDocument as tool7 } from "./read-document/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { runCodeDocument as tool9 } from "./saved-code-execution/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import {
  createSheetDocument as tool10,
  editSheetDocument as tool11,
} from "./sheet-documents/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import {
  createTextDocument as tool13,
  editTextDocument as tool14,
} from "./text-documents/tool";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { wordCount as tool16 } from "./word-count/tool";

const installed = defineToolSet({
  codeExecution: providers.codeExecution,
  createCodeDocument: tool0,
  createSheetDocument: tool10,
  createTextDocument: tool13,
  deleteDocument: tool3,
  editCodeDocument: tool1,
  editSheetDocument: tool11,
  editTextDocument: tool14,
  generateImage: providers.generateImage,
  generateVideo: providers.generateVideo,
  getWeather: tool6,
  readDocument: tool7,
  retrieveUrl: providers.retrieveUrl,
  runCodeDocument: tool9,
  webSearch: providers.webSearch,
  wordCount: tool16,
});
for (const key of Object.keys(customTools)) {
  if (Object.hasOwn(installed, key) || ["deepResearch"].includes(key)) {
    throw new Error(`Duplicate tool registration: ${key}`);
  }
}
// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports, oxc/no-rest-spread-properties -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const tools = { ...installed, ...customTools };

/* oxlint-enable import/max-dependencies */
