// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: edb90175f93013f166f9549676cea094846e9f80748086a54973c9866a20e057
import { defineToolSet } from "@/lib/eve/tool-types";
import { customTools } from "./custom-tools";
import { generateImageTool as tool0 } from "./generate-image/tool";
import { generateVideoTool as tool1 } from "./generate-video/tool";
import { getWeather as tool2 } from "./get-weather/tool";
import { retrieveUrl as tool3 } from "./retrieve-url/tool";
import { webSearch as tool4 } from "./tavily-search/tool";
import { codeExecution as tool5 } from "./vercel-code-execution/tool";
import { wordCount as tool6 } from "./word-count/tool";

const installed = defineToolSet({
  codeExecution: tool5,
  generateImage: tool0,
  generateVideo: tool1,
  getWeather: tool2,
  retrieveUrl: tool3,
  webSearch: tool4,
  wordCount: tool6,
});
for (const key of Object.keys(customTools)) {
  if (Object.hasOwn(installed, key)) {
    throw new Error(`Duplicate tool registration: ${key}`);
  }
}
export const tools = { ...installed, ...customTools };
