// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 1f480fbcb454d40bf317285712f5da4d91b4cfc3a6357672aa9fbdc3e18b3748
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import type { ToolAvailability } from "@/lib/eve/tool-availability";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { researchAvailable as available0 } from "./deep-research/availability";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { deleteDocumentAvailable as available1 } from "./delete-document/availability";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const toolAvailability: Record<string, ToolAvailability> = {
  deepResearch: available0,
  deleteDocument: available1,
};
