// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: c3b5a76b454c8a58d415a02f404c273087ca2339080c8f67ae010cbe5069844a
import type { ToolAvailability } from "@/lib/eve/tool-availability";
import { researchAvailable as available0 } from "./deep-research/availability";
import { deleteDocumentAvailable as available1 } from "./delete-document/availability";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export const toolAvailability: Record<string, ToolAvailability> = {
  deepResearch: available0,
  deleteDocument: available1,
};
