// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 4990c744382b01dfbcbfe1ccb1cc1d8dce5240acbe1c1dc033fb66aa17b4a5f0
import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";
import { customUi } from "./custom-ui";
import { GetWeatherRenderer as renderer0 } from "./get-weather/renderer";
import { RetrieveUrlRenderer as renderer1 } from "./retrieve-url/renderer";
import { WebSearchRenderer as renderer2 } from "./tavily-search/renderer";
import { CodeExecution as renderer3 } from "./vercel-code-execution/renderer";
import { WordCountRenderer as renderer4 } from "./word-count/renderer";

const installed = {
  "tool-getWeather": renderer0,
  "tool-retrieveUrl": renderer1,
  "tool-webSearch": renderer2,
  "tool-codeExecution": renderer3,
  "tool-wordCount": renderer4,
};
for (const key of Object.keys(customUi)) {
  if (Object.hasOwn(installed, key)) {
    throw new Error(`Duplicate renderer registration: ${key}`);
  }
}
export const ui = { ...installed, ...customUi } satisfies ToolRendererRegistry;
