// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 3b4a3a7a6d3bc48fc741da3db0daebfc783e937f1b5d136ecf0fa2bdb4bf51dc
import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";
import { customUi } from "./custom-ui";
import { GenerateImageRenderer as renderer0 } from "./generate-image/renderer";
import { GenerateVideoRenderer as renderer1 } from "./generate-video/renderer";
import { GetWeatherRenderer as renderer2 } from "./get-weather/renderer";
import { RetrieveUrlRenderer as renderer3 } from "./retrieve-url/renderer";
import { SavedCodeRenderer as renderer4 } from "./saved-code-execution/renderer";
import { WebSearchRenderer as renderer5 } from "./tavily-search/renderer";
import { CodeExecution as renderer6 } from "./vercel-code-execution/renderer";
import { WordCountRenderer as renderer7 } from "./word-count/renderer";

const installed = {
  "tool-codeExecution": renderer6,
  "tool-generateImage": renderer0,
  "tool-generateVideo": renderer1,
  "tool-getWeather": renderer2,
  "tool-retrieveUrl": renderer3,
  "tool-runCodeDocument": renderer4,
  "tool-webSearch": renderer5,
  "tool-wordCount": renderer7,
};
for (const key of Object.keys(customUi)) {
  if (Object.hasOwn(installed, key)) {
    throw new Error(`Duplicate renderer registration: ${key}`);
  }
}
export const ui = { ...installed, ...customUi } satisfies ToolRendererRegistry;
