// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 2f51b8d162430d2f3b7f7fc58c235b27bd0cc4521014af89a12997b0973f7ed8
export const urlRetrievalEnvRequirement = {"options":[["FIRECRAWL_API_KEY"]],"description":"FIRECRAWL_API_KEY"};
