// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 6193e1443bc39b6799767a02790ae8c168978bda0339734e48698aaba8a16725
import type { deepResearch as workflow0 } from "./deep-research/tool";

// oxlint-disable-next-line typescript/consistent-type-definitions -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export type WorkflowTools = {
  deepResearch: typeof workflow0;
};
