// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 1fcb2d3f0673f9fb952ec447ba0fc96e20e1d6ded18aaf736446214fd08ce5fe
import type { deepResearch as workflow0 } from "./deep-research/tool";

// oxlint-disable-next-line typescript/consistent-type-definitions, import/no-named-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export type WorkflowTools = {
  deepResearch: typeof workflow0;
};
