// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: d20269d31a0233214c3b3e297c14b5e0141915091e175fbf322577d5f35e3d9d
import type { deepResearch as workflow0 } from "./deep-research/tool";

export type WorkflowTools = {
  deepResearch: typeof workflow0;
};
