import assert from "node:assert/strict";

import { describe, it } from "vitest";

import {
  getFileImageProps,
  isFileStorageKey,
  keyFromFileUrl,
} from "./file-url";

describe("keyFromFileUrl", () => {
  const url = "/api/files/content?key=l_u0a2bkphKLFKsBI4q5Tue9.png";

  it("accepts Next Image deployment metadata", () => {
    assert.equal(
      keyFromFileUrl(`${url}&dpl=dpl_test`),
      "l_u0a2bkphKLFKsBI4q5Tue9.png"
    );
  });

  it("still rejects unknown parameters, duplicate keys and invalid storage keys", () => {
    assert.equal(keyFromFileUrl(`${url}&other=value`), null);
    assert.equal(keyFromFileUrl(`${url}&dpl=dpl_test&other=value`), null);
    assert.equal(keyFromFileUrl(`${url}&key=other&dpl=dpl_test`), null);
    assert.equal(keyFromFileUrl(`${url}&dpl=one&dpl=two`), null);
    assert.equal(
      keyFromFileUrl("/api/files/content?key=../file&dpl=dpl_test"),
      null
    );
  });
});

describe("isFileStorageKey", () => {
  it("recognizes only keys generated by the Files SDK integration", () => {
    assert.equal(isFileStorageKey("l_u0a2bkphKLFKsBI4q5Tue9.png"), true);
    assert.equal(isFileStorageKey("legacy-upload-name.png"), false);
    assert.equal(isFileStorageKey("folder/legacy-upload.png"), false);
  });
});

describe("getFileImageProps", () => {
  it("makes managed worktree files same-origin for Next Image", () => {
    assert.deepEqual(
      getFileImageProps(
        "http://localhost:3030/api/files/content?key=l_u0a2bkphKLFKsBI4q5Tue9.png"
      ),
      {
        src: "/api/files/content?key=l_u0a2bkphKLFKsBI4q5Tue9.png",
        unoptimized: true,
      }
    );
  });

  it("leaves external images unchanged", () => {
    const url = "https://example.com/image.png";
    assert.deepEqual(getFileImageProps(url), { src: url, unoptimized: false });
  });
});
