// oxlint-disable-next-line import/no-nodejs-modules -- Forge packaging runs in Node and needs host process and filesystem APIs before packaging starts.
import { spawnSync } from "node:child_process";
/* oxlint-disable sort-imports -- Preserve runtime module evaluation order; sort-imports requires different binding-syntax groups. */
// oxlint-disable-next-line import/no-nodejs-modules -- Forge packaging runs in Node and needs host process and filesystem APIs before packaging starts.
import { existsSync, readFileSync } from "node:fs";
/* oxlint-enable sort-imports */
// oxlint-disable-next-line import/no-nodejs-modules -- Forge packaging runs in Node and needs host process and filesystem APIs before packaging starts.
import path from "node:path";

/* oxlint-disable sort-imports -- Preserve runtime module evaluation order; sort-imports requires different local-binding order. */
import { MakerDeb } from "@electron-forge/maker-deb";
/* oxlint-enable sort-imports */
/* oxlint-disable sort-imports -- Preserve runtime module evaluation order; sort-imports requires different local-binding order. */
import { MakerDMG } from "@electron-forge/maker-dmg";
/* oxlint-enable sort-imports */
import { MakerRpm } from "@electron-forge/maker-rpm";
import { MakerSquirrel } from "@electron-forge/maker-squirrel";
import { MakerZIP } from "@electron-forge/maker-zip";
/* oxlint-disable sort-imports -- Keep separate type declarations, Oxfmt grouping and runtime module order; their combined ordering conflicts with sort-imports. */
import type { ForgeConfig } from "@electron-forge/shared-types";
/* oxlint-enable sort-imports */

interface Branding {
  appName: string;
  appPrefix: string;
  appUrl: string;
  orgName?: string;
  orgEmail?: string;
}

const appRoot = import.meta.dirname;
const brandingPath = path.join(appRoot, "branding.json");
let prebuildComplete = false;

/* oxlint-disable node/no-sync -- runBunScript: Forge/startup uses synchronous configuration and filesystem contracts before the desktop process is ready. */
/* oxlint-disable node/no-process-env -- runBunScript: This process boundary owns environment loading/forwarding; consumers receive the resulting validated configuration. */
/* oxlint-disable eslint/no-magic-numbers -- runBunScript: Exit/status codes, timeouts and OS/protocol bounds retain this command's operational contract. */
const runBunScript = (
  script: string,
  env: Readonly<Partial<NodeJS.ProcessEnv>> = {}
): void => {
  const result = spawnSync("bun", ["run", script], {
    // oxlint-disable-next-line oxc/no-rest-spread-properties -- Keep the existing process.env own-key composition and positional override order; the pinned eslint/prefer-object-spread rule rejects the Object.assign replacement. Keep the existing env own-key composition and positional override order; the pinned eslint/prefer-object-spread rule rejects the Object.assign replacement.
    env: { ...process.env, ...env },
    stdio: "inherit",
  });

  if (result.status !== 0) {
    throw new Error(
      `bun run ${script} failed with exit code ${result.status ?? "unknown"}`
    );
  }
};
/* oxlint-enable eslint/no-magic-numbers */
/* oxlint-enable node/no-process-env */
/* oxlint-enable node/no-sync */

const ensurePrebuild = (): void => {
  if (prebuildComplete) {
    return;
  }

  runBunScript("prebuild");
  prebuildComplete = true;
};

/* oxlint-disable node/no-sync -- loadBranding: Forge/startup uses synchronous configuration and filesystem contracts before the desktop process is ready. */
/* oxlint-disable eslint/no-undefined -- loadBranding: The API distinguishes omitted/undefined values from null or a concrete result; preserve that sentinel. */
const loadBranding = (): Branding => {
  ensurePrebuild();

  if (!existsSync(brandingPath)) {
    throw new Error(
      `Electron packaging requires ${brandingPath}, but it was not generated by prebuild. ` +
        `Run \`bun run prebuild\` in ${appRoot} and try again.`
    );
  }

  const branding: unknown = JSON.parse(readFileSync(brandingPath, "utf-8"));

  if (
    typeof branding !== "object" ||
    branding === null ||
    !("appName" in branding) ||
    typeof branding.appName !== "string" ||
    !branding.appName ||
    !("appPrefix" in branding) ||
    typeof branding.appPrefix !== "string" ||
    !branding.appPrefix ||
    !("appUrl" in branding) ||
    typeof branding.appUrl !== "string" ||
    !branding.appUrl
  ) {
    throw new Error(
      `Electron branding file ${brandingPath} is invalid. Expected appName, appPrefix, and appUrl.`
    );
  }

  return {
    appName: branding.appName,
    appPrefix: branding.appPrefix,
    appUrl: branding.appUrl,
    orgEmail:
      // oxlint-disable-next-line no-ternary -- Keep orgEmail as a lazy value selection; if/else assignment of these branches conflicts with pinned unicorn/prefer-ternary.
      "orgEmail" in branding && typeof branding.orgEmail === "string"
        ? branding.orgEmail
        : undefined,
    orgName:
      // oxlint-disable-next-line no-ternary -- Keep orgName as a lazy value selection; if/else assignment of these branches conflicts with pinned unicorn/prefer-ternary.
      "orgName" in branding && typeof branding.orgName === "string"
        ? branding.orgName
        : undefined,
  };
};
/* oxlint-enable eslint/no-undefined */
/* oxlint-enable node/no-sync */

/* oxlint-disable eslint/max-lines-per-function -- createForgeConfig: The operation keeps its validation, ordered side effects and cleanup in one scope. */
const createForgeConfig = (): ForgeConfig => {
  const branding = loadBranding();
  const { appName, appPrefix, orgName, orgEmail } = branding;

  /* oxlint-disable oxc/no-async-await -- Modern configured runtimes support native async; preserve callbacks in this return statement's required Promise and rejection contract. generateAssets adapts synchronous ensurePrebuild failures into the Forge hook promise. prePackage adapts synchronous production build failures into the Forge hook promise. preStart adapts synchronous development build failures into the Forge hook promise. */
  return {
    hooks: {
      // oxlint-disable-next-line eslint/require-await, typescript/require-await -- ForgeSimpleHookFn requires a Promise-returning hook; async adapts this synchronous build preparation to that declared contract.
      generateAssets: async () => {
        ensurePrebuild();
      },
      // oxlint-disable-next-line eslint/require-await, typescript/require-await -- ForgeSimpleHookFn requires a Promise-returning hook; async adapts this synchronous build preparation to that declared contract.
      prePackage: async () => {
        runBunScript("build", { NODE_ENV: "production" });
      },
      // oxlint-disable-next-line eslint/require-await, typescript/require-await -- ForgeSimpleHookFn requires a Promise-returning hook; async adapts this synchronous build preparation to that declared contract.
      preStart: async () => {
        runBunScript("build", { NODE_ENV: "development" });
      },
    },
    makers: [
      new MakerZIP({}, ["darwin"]),
      new MakerDMG(
        {
          name: `${appName}-mac`,
        },
        ["darwin"]
      ),
      new MakerSquirrel(
        {
          authors: orgName ?? appName,
          description: `${appName} desktop application`,
          name: appPrefix,
          setupExe: `${appName}-windows.exe`,
        },
        ["win32"]
      ),
      new MakerDeb(
        {
          options: {
            bin: appPrefix,
            categories: ["Utility"],
            homepage: branding.appUrl,
            icon: "./build/icon.png",
            maintainer:
              // oxlint-disable-next-line no-ternary -- Keep maintainer as a lazy value selection; if/else assignment of these branches conflicts with pinned unicorn/prefer-ternary.
              typeof orgName === "string" &&
              orgName !== "" &&
              typeof orgEmail === "string" &&
              orgEmail !== ""
                ? `${orgName} <${orgEmail}>`
                : (orgName ?? orgEmail ?? appName),
          },
        },
        ["linux"]
      ),
      new MakerRpm(
        {
          options: {
            bin: appPrefix,
            homepage: branding.appUrl,
            icon: "./build/icon.png",
            license: "Apache-2.0",
          },
        },
        ["linux"]
      ),
    ],
    packagerConfig: {
      appBundleId: `dev.${appPrefix}.app`,
      appCategoryType: "public.app-category.productivity",
      asar: true,
      executableName: appPrefix,
      icon: "./build/icon",
      ignore: [
        /^\/out(?:$|\/)/u,
        /^\/release(?:$|\/)/u,
        /^\/src(?:$|\/)/u,
        /^\/node_modules(?:$|\/)/u,
        /^\/scripts(?:$|\/)/u,
        /^\/README\.md$/u,
        /^\/tsconfig\.json$/u,
      ],
      name: appName,
      protocols: [
        {
          name: `${appName} Auth`,
          schemes: [appPrefix],
        },
      ],
    },
  };
  /* oxlint-enable oxc/no-async-await */
};
/* oxlint-enable eslint/max-lines-per-function */

const config = createForgeConfig();

/* oxlint-disable import/no-default-export -- forge.config.ts: This framework/tool loader consumes the default entrypoint; changing export shape would break discovery. */
export default config;
/* oxlint-enable import/no-default-export */
