import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile, rm } from "node:fs/promises";
import pathModule from "node:path";

import { toolDefinitionSchema } from "../../../registry/metadata";
import type { ToolDefinition } from "../../../registry/metadata";
import { validateCustomToolKeys } from "./custom-tool-keys";
import { preflight } from "./preflight";

const { join } = pathModule;

const generated =
  "// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.\n";
const hash = (content: string): string =>
  createHash("sha256").update(content).digest("hex");
const readOptional = async (path: string): Promise<string | null> => {
  try {
    return await readFile(path, "utf-8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return null;
    }
    throw error;
  }
};
const generatedSource = (body: string): string => {
  const normalizedBody = body
    .replace(
      "export type WorkflowTools = {\n\n};",
      "export type WorkflowTools = Record<never, never>;"
    )
    .replace(
      "export const toolAvailability: Record<string, ToolAvailability> = {\n\n};",
      "export const toolAvailability: Record<string, ToolAvailability> = {};"
    )
    .replace(
      "const installed = defineToolSet({\n\n});",
      "const installed = defineToolSet({});"
    )
    .replace("const installed = {\n\n};", "const installed = {};")
    .replace(
      "export const documentUi: DocumentUiRegistry = {\n\n};",
      "export const documentUi: DocumentUiRegistry = {};"
    )
    .replace(
      "export const installedDocumentKinds: ReadonlySet<string> = new Set([\n\n]);",
      "export const installedDocumentKinds: ReadonlySet<string> = new Set([]);"
    )
    .replace(";\n\n\nconst installed", ";\n\nconst installed")
    .replace(";\n\n\nexport const documentUi", ";\n\nexport const documentUi");
  return `${generated}// Content: ${hash(normalizedBody)}\n${normalizedBody}`;
};
const checkGenerated = (content: string | null, path: string): void => {
  if (!content) {
    return;
  }
  const lines = content.split("\n");
  if (
    !content.startsWith(generated) ||
    lines[1] !== `// Content: ${hash(lines.slice(2).join("\n"))}`
  ) {
    throw new Error(
      `${path} contains custom or legacy registrations. Preserve them in custom-tools.ts/custom-ui.ts and remove the old generated index before running chat-js sync.`
    );
  }
};

const selections = {
  codeExecution: {
    file: "code-execution",
    requirement: "codeExecutionEnvRequirement",
  },
  generateImage: {
    file: "image-generation",
    requirement: "imageGenerationEnvRequirement",
  },
  generateVideo: {
    file: "video-generation",
    requirement: "videoGenerationEnvRequirement",
  },
  retrieveUrl: {
    file: "url-retrieval",
    requirement: "urlRetrievalEnvRequirement",
  },
  webSearch: { file: "search", requirement: "searchEnvRequirement" },
} as const;
const selectionFiles = Object.values(selections).flatMap(({ file }) => [
  `${file}.ts`,
  `${file}-config.ts`,
]);
const registrationsFor = (definitions: ToolDefinition[]) =>
  definitions.flatMap((item) =>
    item.tools.map((tool) => ({
      ...tool,
      id: item.id,
      key: item.slot ?? tool.toolExport,
      provider: Boolean(item.slot),
    }))
  );

type Registration = ReturnType<typeof registrationsFor>[number];
const registrationKey = (item: Registration): string => item.key;

const readToolDefinition = async (
  cwd: string,
  directory: string,
  entryName: string
): Promise<ToolDefinition | null> => {
  const descriptor = `${directory}/${entryName}/chatjs.json`;
  await preflight(cwd, [descriptor]);
  const content = await readOptional(join(cwd, descriptor));
  if (!content) {
    return null;
  }
  const definition = toolDefinitionSchema.parse(JSON.parse(content));
  if (definition.id !== entryName) {
    throw new Error(
      `Tool descriptor id must match its directory: ${entryName}`
    );
  }
  await preflight(cwd, [
    `${directory}/${entryName}/tool.ts`,
    ...(definition.availabilityExport
      ? [`${directory}/${entryName}/availability.ts`]
      : []),
    ...definition.tools
      .filter((tool) => tool.workflow)
      .map((tool) => `agent/tools/${tool.toolExport}.ts`),
    ...(definition.documentKind || definition.documentRunExport
      ? [`${directory}/${entryName}/document.tsx`]
      : []),
    ...(definition.tools.some((tool) => tool.rendererExport)
      ? [`${directory}/${entryName}/renderer.tsx`]
      : []),
  ]);
  await Promise.all([
    readFile(join(cwd, directory, entryName, "tool.ts")),
    ...definition.tools
      .filter((tool) => tool.workflow)
      .map((tool) =>
        readFile(join(cwd, "agent/tools", `${tool.toolExport}.ts`))
      ),
    ...(definition.documentKind || definition.documentRunExport
      ? [readFile(join(cwd, directory, entryName, "document.tsx"))]
      : []),
    ...(definition.tools.some((tool) => tool.rendererExport)
      ? [readFile(join(cwd, directory, entryName, "renderer.tsx"))]
      : []),
  ]);
  return definition;
};

const collectDefinitions = async (
  cwd: string,
  directory: string,
  entries: Awaited<ReturnType<typeof readdir>>,
  definitions: ToolDefinition[],
  index = 0
): Promise<void> => {
  const entry = entries[index];
  if (!entry) {
    return;
  }
  if (entry.isSymbolicLink()) {
    throw new Error(`Tool directories must not be symlinks: ${entry.name}`);
  }
  if (entry.isDirectory() && !entry.name.startsWith("_")) {
    const definition = await readToolDefinition(cwd, directory, entry.name);
    if (definition) {
      const existing = definitions.findIndex(
        (item) => item.id === definition.id
      );
      if (existing !== -1) {
        definitions.splice(existing, 1);
      }
      definitions.push(definition);
    }
  }
  await collectDefinitions(cwd, directory, entries, definitions, index + 1);
};

const validateGeneratedSelections = async (dir: string): Promise<void> => {
  const contents = await Promise.all(
    selectionFiles.map(async (filename) => ({
      content: await readOptional(join(dir, filename)),
      filename,
    }))
  );
  for (const { content, filename } of contents) {
    checkGenerated(content, filename);
  }
};

const missingPreviousRegistration = (
  previousTools: string | null,
  ids: Set<string>,
  entries: Awaited<ReturnType<typeof readdir>>
): string | null => {
  for (const match of previousTools?.matchAll(
    /from "\.\/(?<id>[a-z][a-z0-9-]*)\/tool"/gu
  ) ?? []) {
    const id = match.groups?.id;
    if (!ids.has(id ?? "") && entries.some((entry) => entry.name === id)) {
      return id ?? "";
    }
  }
  return null;
};

const validateExpected = (
  definitions: ToolDefinition[],
  expected: ToolDefinition[]
): void => {
  for (const requested of expected) {
    const installed = definitions.find((item) => item.id === requested.id);
    if (!installed || JSON.stringify(installed) !== JSON.stringify(requested)) {
      throw new Error(
        `Installed descriptor does not match requested tool ${requested.id}. Check the registry item's files and overwrite choices.`
      );
    }
  }
};

const validateSelections = (definitions: ToolDefinition[]): void => {
  for (const slot of Object.keys(selections)) {
    if (definitions.filter((item) => item.slot === slot).length > 1) {
      throw new Error(
        `Only one ${slot} tool can be selected. Remove the previous tool directory before syncing.`
      );
    }
  }
};

const buildEnvironmentOptions = (
  selected: ToolDefinition | undefined
): string[][] => {
  if (!selected) {
    return [];
  }
  let combinations: string[][] = [[]];
  for (const requirement of selected.envRequirements) {
    const next: string[][] = [];
    for (const credentialSet of combinations) {
      for (const option of requirement.options) {
        next.push([...credentialSet, ...option]);
      }
    }
    combinations = next;
  }
  return combinations;
};

const writeSelectionConfigs = async (
  dir: string,
  definitions: ToolDefinition[],
  entries = Object.entries(selections),
  index = 0
): Promise<void> => {
  const entry = entries[index];
  if (!entry) {
    return;
  }
  const [slot, spec] = entry;
  const selected = definitions.find((item) => item.slot === slot);
  const envOptions = buildEnvironmentOptions(selected);
  await rm(join(dir, `${spec.file}.ts`), { force: true });
  await writeFile(
    join(dir, `${spec.file}-config.ts`),
    generatedSource(
      `export const ${spec.requirement} = ${JSON.stringify({ ...(selected?.envRequirements.some((requirement) => requirement.runtimeAuth) ? { allOf: selected.envRequirements } : {}), description: selected ? envOptions.map((credentialSet) => credentialSet.join(" + ")).join(" or ") : `Install a ${slot} tool`, options: envOptions })};\n${slot === "codeExecution" ? `export const supportsSavedDocuments = ${Boolean(selected?.codeExecutorExport)};\n` : ""}`
    )
  );
  await writeSelectionConfigs(dir, definitions, entries, index + 1);
};

const orderedProperties = (properties: { key: string; value: string }[]) =>
  properties
    .toSorted((a, b) => {
      if (a.key === b.key) {
        return 0;
      }
      return a.key < b.key ? -1 : 1;
    })
    .map(({ key, value }) => `  ${key}: ${value},`)
    .join("\n");

const registrationImports = (
  entries: { id: string; name: string; alias: string }[],
  file: "tool" | "renderer"
) => {
  const groups = new Map<string, string[]>();
  for (const item of entries) {
    const names = groups.get(item.id) ?? [];
    names.push(`${item.name} as ${item.alias}`);
    groups.set(item.id, names);
  }
  return [...groups]
    .map(([id, names]) =>
      names.length === 1
        ? `import { ${names[0]} } from "./${id}/${file}";`
        : `import {\n${names.map((name) => `  ${name},`).join("\n")}\n} from "./${id}/${file}";`
    )
    .join("\n");
};

const sourceFor = (
  registrations: Registration[]
): { providerBody: string; toolBody: string; uiBody: string } => {
  const renderers = registrations.filter((item) => item.rendererExport);
  const providers = registrations.filter((item) => item.provider);
  const ordinary = registrations.filter((item) => !item.workflow);
  return {
    providerBody: `import { defineToolSet } from "@/lib/eve/tool-types";\n${registrationImports(
      providers.map((item, i) => ({
        alias: `tool${i}`,
        id: item.id,
        name: item.toolExport,
      })),
      "tool"
    )}\n\nexport const providers = defineToolSet({\n${orderedProperties(providers.map((item, i) => ({ key: registrationKey(item), value: `tool${i}` })))}\n});\n`,
    toolBody: `import { defineToolSet } from "@/lib/eve/tool-types";\nimport { customTools } from "./custom-tools";\nimport { providers } from "./providers";\n${registrationImports(
      ordinary
        .filter((item) => !item.provider)
        .map((item) => ({
          alias: `tool${registrations.indexOf(item)}`,
          id: item.id,
          name: item.toolExport,
        })),
      "tool"
    )}\n\nconst installed = defineToolSet({\n${orderedProperties(ordinary.map((item) => ({ key: registrationKey(item), value: item.provider ? `providers.${item.key}` : `tool${registrations.indexOf(item)}` })))}\n});\nfor (const key of Object.keys(customTools)) {\n  if (Object.hasOwn(installed, key)${registrations.some((item) => item.workflow) ? ` || ${JSON.stringify(registrations.filter((item) => item.workflow).map((item) => item.key))}.includes(key)` : ""}) {\n    throw new Error(\`Duplicate tool registration: \${key}\`);\n  }\n}\nexport const tools = { ...installed, ...customTools };\n`,
    uiBody: `import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";\nimport { customUi } from "./custom-ui";\n${registrationImports(
      renderers.flatMap((item, i) =>
        item.rendererExport
          ? [{ alias: `renderer${i}`, id: item.id, name: item.rendererExport }]
          : []
      ),
      "renderer"
    )}\n\nconst installed = {\n${orderedProperties(renderers.map((item, i) => ({ key: JSON.stringify(`tool-${registrationKey(item)}`), value: `renderer${i}` })))}\n};\nfor (const key of Object.keys(customUi)) {\n  if (Object.hasOwn(installed, key)) {\n    throw new Error(\`Duplicate renderer registration: \${key}\`);\n  }\n}\nexport const ui = { ...installed, ...customUi } satisfies ToolRendererRegistry;\n`,
  };
};

const validateToolDependencies = (definitions: ToolDefinition[]): void => {
  const availableKeys = new Set(
    registrationsFor(definitions).map(registrationKey)
  );
  for (const definition of definitions) {
    const missingTools = definition.requiresTools.filter(
      (name) => !availableKeys.has(name)
    );
    if (missingTools.length > 0) {
      throw new Error(
        `${definition.id} requires installed tools: ${missingTools.join(", ")}`
      );
    }
  }
  const runners = definitions.filter((item) => item.documentRunExport);
  if (runners.length > 1) {
    throw new Error("Only one saved-document executor can be installed.");
  }
  const executor = definitions.find((item) => item.slot === "codeExecution");
  if (
    registrationsFor(definitions).some(
      (item) => registrationKey(item) === "runCodeDocument"
    ) &&
    !executor?.codeExecutorExport
  ) {
    throw new Error(
      "Saved code execution requires a compatible codeExecution provider, such as vercel-code-execution."
    );
  }
};

export const readInstalledTools = async (
  cwd: string
): Promise<ToolDefinition[]> => {
  const directory = "tools/chatjs";
  const targets = [
    "tools.ts",
    "ui.ts",
    "document-ui.ts",
    "installed-features.ts",
    "composer-tools.ts",
    "document-run.ts",
    "providers.ts",
    "code-executor.ts",
    "workflow-types.ts",
    "tool-availability.ts",
    "custom-tools.ts",
    "custom-ui.ts",
    ...selectionFiles,
  ].map((file) => `${directory}/${file}`);
  await preflight(cwd, targets);
  const dir = join(cwd, directory);
  const entries = await readdir(dir, { withFileTypes: true }).catch((error) => {
    if (error.code === "ENOENT") {
      return [];
    }
    throw error;
  });
  const toolsPath = join(dir, "tools.ts");
  const uiPath = join(dir, "ui.ts");
  const previousTools = await readOptional(toolsPath);
  const previousUi = await readOptional(uiPath);
  await validateGeneratedSelections(dir);
  checkGenerated(previousTools, toolsPath);
  checkGenerated(previousUi, uiPath);
  await Promise.all(
    [
      "document-ui.ts",
      "installed-features.ts",
      "composer-tools.ts",
      "document-run.ts",
      "providers.ts",
      "code-executor.ts",
      "workflow-types.ts",
      "tool-availability.ts",
    ].map(async (file) => {
      checkGenerated(await readOptional(join(dir, file)), file);
    })
  );
  const definitions: ToolDefinition[] = [];
  await collectDefinitions(cwd, directory, entries, definitions);
  const ids = new Set(definitions.map((item) => item.id));
  const previousProviders = await readOptional(join(dir, "providers.ts"));
  const previousWorkflows = await readOptional(join(dir, "workflow-types.ts"));
  const missing = missingPreviousRegistration(
    `${previousTools ?? ""}\n${previousProviders ?? ""}\n${previousWorkflows ?? ""}`,
    ids,
    entries
  );
  if (missing) {
    throw new Error(
      `Missing descriptor for previously registered tool: ${missing}. Restore chatjs.json before syncing.`
    );
  }
  return definitions.toSorted((a, b) => a.id.localeCompare(b.id));
};

export const validateToolInstallation = (
  cwd: string,
  definitions: ToolDefinition[]
): void => {
  validateSelections(definitions);
  const documents = definitions.filter((item) => item.documentKind);
  if (
    new Set(documents.map((item) => item.documentKind)).size !==
    documents.length
  ) {
    throw new Error("Only one bundle per document kind can be installed.");
  }
  const keys = registrationsFor(definitions).map(registrationKey);
  if (new Set(keys).size !== keys.length) {
    throw new Error("Duplicate installed tool registration key.");
  }
  validateCustomToolKeys(cwd, definitions);
  validateToolDependencies(definitions);
};

export const syncTools = async (
  cwd: string,
  options: { checkOnly?: boolean; expected?: ToolDefinition[] } = {}
): Promise<ToolDefinition[]> => {
  const definitions = await readInstalledTools(cwd);
  validateExpected(definitions, options.expected ?? []);
  validateToolInstallation(cwd, definitions);
  if (options.checkOnly) {
    return definitions;
  }
  const dir = join(cwd, "tools/chatjs");
  const toolsPath = join(dir, "tools.ts");
  const uiPath = join(dir, "ui.ts");
  const documents = definitions.filter((item) => item.documentKind);
  const registrations = registrationsFor(definitions);
  const keys = registrations.map(registrationKey);
  const { providerBody, toolBody, uiBody } = sourceFor(registrations);
  await mkdir(dir, { recursive: true });
  const [customTools, customUi] = await Promise.all([
    readOptional(join(dir, "custom-tools.ts")),
    readOptional(join(dir, "custom-ui.ts")),
  ]);
  await Promise.all([
    ...(customTools === null
      ? [
          writeFile(
            join(dir, "custom-tools.ts"),
            'import { defineToolSet } from "@/lib/eve/tool-types";\n\nexport const customTools = defineToolSet({});\n'
          ),
        ]
      : []),
    ...(customUi === null
      ? [
          writeFile(
            join(dir, "custom-ui.ts"),
            'import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";\n\nexport const customUi = {} satisfies Partial<ToolRendererRegistry>;\n'
          ),
        ]
      : []),
  ]);
  await writeFile(
    join(dir, "document-ui.ts"),
    generatedSource(
      `"use client";\n\nimport type { DocumentUiRegistry } from "@/lib/eve/document-ui";\n\n${documents.map((item, index) => `import { documentUi as document${index} } from "./${item.id}/document";`).join("\n")}\n\nexport const documentUi: DocumentUiRegistry = {\n${documents.map((item, index) => `  ${item.documentKind}: document${index},`).join("\n")}\n};\n`
    )
  );
  await writeFile(
    join(dir, "installed-features.ts"),
    generatedSource(
      `export const installedToolNames: ReadonlySet<string> = new Set(${JSON.stringify(keys)});\nexport const installedDocumentKinds: ReadonlySet<string> = new Set([\n${documents.map((item) => `  ${JSON.stringify(item.documentKind)},`).join("\n")}\n]);\n`
    )
  );
  const composerTools = registrations
    .filter((item) => item.composer)
    .toSorted((a, b) => a.key.localeCompare(b.key));
  await writeFile(
    join(dir, "composer-tools.ts"),
    generatedSource(
      `import type { LucideIcon } from "lucide-react";\n${composerTools.length ? `import { ${composerTools.map((item, index) => `${item.composer?.icon} as Icon${index}`).join(", ")} } from "lucide-react";` : ""}\n\nexport const composerTools: Readonly<Record<string, { icon: LucideIcon; name: string; shortName: string } | undefined>> = ${composerTools.length ? `{\n${composerTools.map((item, index) => `  ${JSON.stringify(item.key)}: { icon: Icon${index}, name: ${JSON.stringify(item.composer?.name)}, shortName: ${JSON.stringify(item.composer?.shortName)} },`).join("\n")}\n}` : "{}"};\n`
    )
  );
  const runner = definitions.find((item) => item.documentRunExport);
  await writeFile(
    join(dir, "document-run.ts"),
    generatedSource(
      `"use client";\n\nimport type { ComponentType } from "react";\n\nimport type { DocumentRunProps } from "@/lib/eve/document-ui";\n${runner ? `\nimport { ${runner.documentRunExport} as InstalledDocumentRun } from "./${runner.id}/document";\n` : ""}\nexport const DocumentRun: ComponentType<DocumentRunProps> | undefined =\n  ${runner ? "InstalledDocumentRun" : "undefined"};\n`
    )
  );
  await writeSelectionConfigs(dir, definitions);
  await writeFile(join(dir, "providers.ts"), generatedSource(providerBody));
  const executor = definitions.find((item) => item.codeExecutorExport);
  await writeFile(
    join(dir, "code-executor.ts"),
    generatedSource(
      `import type { CodeExecutor } from "@/lib/eve/code-executor";\n${executor ? `import { ${executor.codeExecutorExport} as execute } from "./${executor.id}/tool";\n` : ""}\nexport const codeExecutor: CodeExecutor | undefined = ${executor ? "execute" : "undefined"};\n`
    )
  );
  const workflows = registrations.filter((item) => item.workflow);
  await writeFile(
    join(dir, "workflow-types.ts"),
    generatedSource(
      `${workflows.map((item, i) => `import type { ${item.toolExport} as workflow${i} } from "./${item.id}/tool";`).join("\n")}\n\nexport type WorkflowTools = {\n${workflows.map((item, i) => `  ${item.key}: typeof workflow${i};`).join("\n")}\n};\n`
    )
  );
  const availability = definitions.filter((item) => item.availabilityExport);
  await writeFile(
    join(dir, "tool-availability.ts"),
    generatedSource(
      `import type { ToolAvailability } from "@/lib/eve/tool-availability";\n${availability.map((item, i) => `import { ${item.availabilityExport} as available${i} } from "./${item.id}/availability";`).join("\n")}\n\nexport const toolAvailability: Record<string, ToolAvailability> = {\n${availability.flatMap((item, i) => item.tools.map((tool) => `  ${item.slot ?? tool.toolExport}: available${i},`)).join("\n")}\n};\n`
    )
  );
  await writeFile(toolsPath, generatedSource(toolBody));
  await writeFile(uiPath, generatedSource(uiBody));
  return definitions;
};
