import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
	toolDefinitionSchema,
	type ToolDefinition,
} from "../../../registry/metadata";
import { legacyTools } from "./legacy-tools";
import { preflight } from "./preflight";

const generated =
	"// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.\n";
function hash(content: string) {
	return createHash("sha256").update(content).digest("hex");
}
async function readOptional(path: string) {
	return readFile(path, "utf8").catch((error) => {
		if (error.code === "ENOENT") return null;
		throw error;
	});
}
function generatedSource(body: string) {
	body = body
		.replace("const installed = {\n\n};", "const installed = {};")
		.replace(";\n\n\nconst installed", ";\n\nconst installed");
	return `${generated}// Content: ${hash(body)}\n${body}`;
}
function checkGenerated(content: string | null, path: string) {
	if (!content) return;
	const lines = content.split("\n");
	if (
		!content.startsWith(generated) ||
		lines[1] !== `// Content: ${hash(lines.slice(2).join("\n"))}`
	)
		throw new Error(
			`${path} contains custom or legacy registrations. Preserve them in custom-tools.ts/custom-ui.ts and remove the old generated index before running chat-js sync.`,
		);
}

export async function syncTools(
	cwd: string,
	options: { checkOnly?: boolean; expected?: ToolDefinition[] } = {},
) {
	const directory = "tools/chatjs";
	const targets = [
		"tools.ts",
		"ui.ts",
		"custom-tools.ts",
		"custom-ui.ts",
		"search.ts",
		"search-config.ts",
	].map((file) => `${directory}/${file}`);
	await preflight(cwd, targets);
	const dir = join(cwd, directory);
	const entries = await readdir(dir, { withFileTypes: true }).catch((error) => {
		if (error.code === "ENOENT") return [];
		throw error;
	});
	const toolsPath = join(dir, "tools.ts");
	const uiPath = join(dir, "ui.ts");
	const previousTools = await readOptional(toolsPath);
	const previousUi = await readOptional(uiPath);
	const legacy =
		previousTools && previousUi && !previousTools.startsWith(generated)
			? await legacyTools(cwd, previousTools, previousUi)
			: null;
	for (const filename of ["search.ts", "search-config.ts"])
		checkGenerated(await readOptional(join(dir, filename)), filename);
	if (!legacy) {
		checkGenerated(previousTools, toolsPath);
		checkGenerated(previousUi, uiPath);
	}
	const definitions = [...(legacy ?? [])];
	for (const entry of entries) {
		if (entry.isSymbolicLink())
			throw new Error(`Tool directories must not be symlinks: ${entry.name}`);
		if (!entry.isDirectory() || entry.name.startsWith("_")) continue;
		const descriptor = `${directory}/${entry.name}/chatjs.json`;
		await preflight(cwd, [descriptor]);
		const content = await readOptional(join(cwd, descriptor));
		if (!content) continue;
		const definition = toolDefinitionSchema.parse(JSON.parse(content));
		if (definition.id !== entry.name)
			throw new Error(
				`Tool descriptor id must match its directory: ${entry.name}`,
			);
		await preflight(cwd, [
			`${directory}/${entry.name}/tool.ts`,
			...(definition.rendererExport
				? [`${directory}/${entry.name}/renderer.tsx`]
				: []),
		]);
		await readFile(join(dir, entry.name, "tool.ts"));
		if (definition.rendererExport)
			await readFile(join(dir, entry.name, "renderer.tsx"));
		const existing = definitions.findIndex((item) => item.id === definition.id);
		if (existing !== -1) definitions.splice(existing, 1);
		definitions.push(definition);
	}
	const ids = new Set(definitions.map((item) => item.id));
	for (const match of previousTools?.matchAll(
		/from "\.\/([a-z][a-z0-9-]*)\/tool"/g,
	) ?? []) {
		if (!ids.has(match[1]))
			throw new Error(
				`Missing descriptor for previously registered tool: ${match[1]}. Restore chatjs.json before syncing.`,
			);
	}
	for (const expected of options.expected ?? []) {
		const installed = definitions.find((item) => item.id === expected.id);
		if (!installed || JSON.stringify(installed) !== JSON.stringify(expected)) {
			throw new Error(
				`Installed descriptor does not match requested tool ${expected.id}. Check the registry item's files and overwrite choices.`,
			);
		}
	}
	definitions.sort((a, b) => a.id.localeCompare(b.id));
	const searchTools = definitions.filter((item) => item.slot === "webSearch");
	if (searchTools.length > 1)
		throw new Error(
			"Only one webSearch tool can be selected. Remove the previous search tool directory before syncing.",
		);
	const registrations = definitions.filter((item) => !item.slot);
	const renderers = registrations.filter((item) => item.rendererExport);
	const keys = registrations.map((item) => item.toolExport);
	if (new Set(keys).size !== keys.length)
		throw new Error("Duplicate installed tool registration key.");
	if (options.checkOnly) return definitions;
	const toolBody = `import { customTools } from "./custom-tools";\n${registrations.map((item, i) => `import { ${item.toolExport} as tool${i} } from "./${item.id}/tool";`).join("\n")}\n\nconst installed = {\n${registrations.map((item, i) => `  ${item.toolExport}: tool${i},`).join("\n")}\n};\nfor (const key of Object.keys(customTools)) {\n  if (Object.hasOwn(installed, key)) {\n    throw new Error(\`Duplicate tool registration: \${key}\`);\n  }\n}\nexport const tools = { ...installed, ...customTools };\n`;
	const uiBody = `import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";\nimport { customUi } from "./custom-ui";\n${renderers.map((item, i) => `import { ${item.rendererExport} as renderer${i} } from "./${item.id}/renderer";`).join("\n")}\n\nconst installed = {\n${renderers.map((item, i) => `  ${JSON.stringify(`tool-${item.toolExport}`)}: renderer${i},`).join("\n")}\n};\nfor (const key of Object.keys(customUi)) {\n  if (Object.hasOwn(installed, key)) {\n    throw new Error(\`Duplicate renderer registration: \${key}\`);\n  }\n}\nexport const ui = { ...installed, ...customUi } satisfies ToolRendererRegistry;\n`;
	await mkdir(dir, { recursive: true });
	if ((await readOptional(join(dir, "custom-tools.ts"))) === null)
		await writeFile(
			join(dir, "custom-tools.ts"),
			'import type { ToolSet } from "ai";\n\nexport const customTools = {} satisfies ToolSet;\n',
		);
	if ((await readOptional(join(dir, "custom-ui.ts"))) === null)
		await writeFile(
			join(dir, "custom-ui.ts"),
			'import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";\n\nexport const customUi = {} satisfies Partial<ToolRendererRegistry>;\n',
		);
	for (const definition of legacy ?? []) {
		const descriptor = join(dir, definition.id, "chatjs.json");
		if ((await readOptional(descriptor)) === null)
			await writeFile(descriptor, `${JSON.stringify(definition, null, 2)}\n`);
	}
	if (searchTools[0]) {
		const search = searchTools[0];
		await writeFile(
			join(dir, "search.ts"),
			generatedSource(
				`import type { SearchToolFactory } from "@/tools/platform/search-presentation";\nimport { ${search.toolExport} } from "./${search.id}/tool";\nconst selectedSearch = ${search.toolExport} satisfies SearchToolFactory;\nexport { selectedSearch as createWebSearch };\n`,
			),
		);
	} else {
		await writeFile(
			join(dir, "search.ts"),
			generatedSource(
				`import { tool } from "ai";\nimport { z } from "zod";\nexport const createWebSearch = (_options: unknown) => tool({ description: "Search is not installed", inputSchema: z.object({}), execute: async () => { throw new Error("Install a webSearch tool using chat-js add."); } });\n`,
			),
		);
	}
	const requirements = searchTools[0]?.envRequirements ?? [];
	const envOptions = searchTools[0]
		? requirements.reduce<string[][]>(
				(all, requirement) =>
					all.flatMap((keys) =>
						requirement.options.map((option) => [...keys, ...option]),
					),
				[[]],
			)
		: [];
	await writeFile(
		join(dir, "search-config.ts"),
		generatedSource(
			`export const searchEnvRequirement = ${JSON.stringify({ options: envOptions, description: searchTools[0] ? envOptions.map((keys) => keys.join(" + ")).join(" or ") : "Install a webSearch tool" })};\n`,
		),
	);
	await writeFile(toolsPath, generatedSource(toolBody));
	await writeFile(uiPath, generatedSource(uiBody));
	return definitions;
}
