// oxlint-disable-next-line import/no-nodejs-modules -- The Node/Bun CLI hashes installed source using the native cryptographic implementation.
import { createHash } from "node:crypto";
// oxlint-disable-next-line import/no-nodejs-modules -- The Node/Bun CLI reads, writes, and validates real project files with native filesystem APIs.
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
// oxlint-disable-next-line import/no-nodejs-modules -- The Node/Bun CLI resolves platform-specific project and installation paths.
import pathModule from "node:path";

import type { ReadonlyInput } from "#cli/helpers/readonly-input";

// oxlint-disable-next-line import/no-relative-parent-imports -- Shared registry descriptors outside the CLI package are bundled into the published executable.
import { toolDefinitionSchema } from "../../../registry/metadata";
// oxlint-disable-next-line import/no-relative-parent-imports -- Shared registry descriptor types live outside the CLI package.
import type { ToolDefinition } from "../../../registry/metadata";
import { validateCustomToolKeys } from "./custom-tool-keys";
import { generatedRegistrationSource } from "./generated-registration-source";
import { preflight } from "./preflight";

const generated =
  "// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.\n";
const hash = (content: string): string =>
  createHash("sha256").update(content).digest("hex");
/* oxlint-disable unicorn/no-null -- Null is an explicit SDK, serialized-data, or React absence sentinel; replacing it would change the contract. */
const readOptional = async (path: string): Promise<string | null> => {
  try {
    return await readFile(path, "utf-8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return null;
    }
    throw error;
  }
};
/* oxlint-enable unicorn/no-null */
const generatedSource = (body: string): string => {
  const normalizedBody = body
    .replace(
      "export type WorkflowTools = {\n\n};",
      "export type WorkflowTools = Record<never, never>;"
    )
    .replace(
      "export const toolAvailability: Record<string, ToolAvailability> = {\n\n};",
      "export const toolAvailability: Record<string, ToolAvailability> = {};"
    )
    .replace(
      "const installed = defineToolSet({\n\n});",
      "const installed = defineToolSet({});"
    )
    .replace("const installed = {\n\n};", "const installed = {};")
    .replace(
      "export const documentUi: DocumentUiRegistry = {\n\n};",
      "export const documentUi: DocumentUiRegistry = {};"
    )
    .replace(
      "export const installedDocumentKinds: ReadonlySet<string> = new Set([\n\n]);",
      "export const installedDocumentKinds: ReadonlySet<string> = new Set([]);"
    )
    .replace(";\n\n\nconst installed", ";\n\nconst installed")
    .replace(";\n\n\nexport const documentUi", ";\n\nexport const documentUi");
  const registrations = generatedRegistrationSource(normalizedBody);
  return `${generated}// Content: ${hash(registrations)}\n${registrations}`;
};
/* oxlint-disable eslint/no-magic-numbers -- These literals encode local protocol limits, indexing, or fixture expectations; keep them beside the operation whose units they describe. */
const checkGenerated = (content: string | null, path: string): void => {
  if (!(typeof content === "string" && content !== "")) {
    return;
  }
  const lines = content.split("\n");
  if (
    !content.startsWith(generated) ||
    lines[1] !== `// Content: ${hash(lines.slice(2).join("\n"))}`
  ) {
    throw new Error(
      `${path} contains custom or legacy registrations. Preserve them in custom-tools.ts/custom-ui.ts and remove the old generated index before running chat-js sync.`
    );
  }
};
/* oxlint-enable eslint/no-magic-numbers */

const selectionSlots = [
  "codeExecution",
  "generateImage",
  "generateVideo",
  "retrieveUrl",
  "webSearch",
] as const;
/* oxlint-disable typescript/explicit-function-return-type -- Preserve the inferred structural or generic result so caller-specific schema and SDK types are not widened. */
const registrationsFor = (
  definitions: readonly ReadonlyInput<ToolDefinition>[]
) =>
  definitions.flatMap((item) =>
    item.tools.map((tool) => ({
      ...tool,
      id: item.id,
      key: item.slot ?? tool.toolExport,
      provider: Boolean(item.slot),
    }))
  );
/* oxlint-enable typescript/explicit-function-return-type */

type Registration = ReturnType<typeof registrationsFor>[number];
/* oxlint-disable typescript/prefer-readonly-parameter-types -- This parameter participates in the existing SDK or mutable state contract; recursively readonly types would change assignability or permitted updates. */
const registrationKey = (item: Registration): string => item.key;
/* oxlint-disable eslint/max-lines-per-function -- Keep the ordered validation, state transitions, and cleanup in one operation so their sequencing remains reviewable. */
/* oxlint-enable typescript/prefer-readonly-parameter-types */

/* oxlint-disable eslint/max-statements -- These statements express one ordered operation with shared validation and cleanup; preserve the existing sequencing. */
/* oxlint-disable unicorn/no-null -- Null is an explicit SDK, serialized-data, or React absence sentinel; replacing it would change the contract. */
/* oxlint-disable typescript/strict-boolean-expressions -- This value-producing condition preserves the current nullish/empty sentinel behavior; coercing it would change the returned value. */
/* oxlint-disable typescript/promise-function-async -- Return the existing promise directly to preserve its identity and the current synchronous-throw boundary. */
const readToolDefinition = async (
  cwd: string,
  directory: string,
  entryName: string
): Promise<ToolDefinition | null> => {
  const descriptor = `${directory}/${entryName}/chatjs.json`;
  await preflight(cwd, [descriptor]);
  const content = await readOptional(pathModule.join(cwd, descriptor));
  if (!(typeof content === "string" && content !== "")) {
    return null;
  }
  const definition = toolDefinitionSchema.parse(JSON.parse(content));
  if (definition.id !== entryName) {
    throw new Error(
      `Tool descriptor id must match its directory: ${entryName}`
    );
  }
  await preflight(cwd, [
    `${directory}/${entryName}/tool.ts`,
    ...(typeof definition.availabilityExport === "string" &&
    definition.availabilityExport !== ""
      ? [`${directory}/${entryName}/availability.ts`]
      : []),
    ...definition.tools
      .filter((tool) => tool.workflow)
      .map((tool): string => `agent/tools/${tool.toolExport}.ts`),
    ...(definition.documentKind ||
    (typeof definition.documentRunExport === "string" &&
      definition.documentRunExport !== "")
      ? [`${directory}/${entryName}/document.tsx`]
      : []),
    ...(definition.tools.some((tool) => tool.rendererExport)
      ? [`${directory}/${entryName}/renderer.tsx`]
      : []),
  ]);
  await Promise.all([
    readFile(pathModule.join(cwd, directory, entryName, "tool.ts")),
    ...definition.tools
      .filter((tool) => tool.workflow)
      .map((tool) =>
        readFile(pathModule.join(cwd, "agent/tools", `${tool.toolExport}.ts`))
      ),
    ...(definition.documentKind ||
    (typeof definition.documentRunExport === "string" &&
      definition.documentRunExport !== "")
      ? [readFile(pathModule.join(cwd, directory, entryName, "document.tsx"))]
      : []),
    ...(definition.tools.some((tool) => tool.rendererExport)
      ? [readFile(pathModule.join(cwd, directory, entryName, "renderer.tsx"))]
      : []),
  ]);
  return definition;
};
/* oxlint-enable eslint/max-lines-per-function */
/* oxlint-enable typescript/promise-function-async */
/* oxlint-enable typescript/strict-boolean-expressions */
/* oxlint-enable unicorn/no-null */
/* oxlint-enable eslint/max-statements */

/* oxlint-disable eslint/max-statements -- These statements express one ordered operation with shared validation and cleanup; preserve the existing sequencing. */
/* oxlint-disable eslint/max-params -- This adapter implements the existing positional callback contract; changing it requires updating every caller. */
/* oxlint-disable eslint/no-magic-numbers -- These literals encode local protocol limits, indexing, or fixture expectations; keep them beside the operation whose units they describe. */
/* oxlint-disable typescript/prefer-readonly-parameter-types -- This parameter participates in the existing SDK or mutable state contract; recursively readonly types would change assignability or permitted updates. */
/* oxlint-disable typescript/strict-boolean-expressions -- This value-producing condition preserves the current nullish/empty sentinel behavior; coercing it would change the returned value. */
const collectDefinitions = async (
  cwd: string,
  directory: string,
  entries: Awaited<ReturnType<typeof readdir>>,
  definitions: ToolDefinition[],
  index = 0
): Promise<void> => {
  const entry = entries[index];
  if (!entry) {
    return;
  }
  if (entry.isSymbolicLink()) {
    throw new Error(`Tool directories must not be symlinks: ${entry.name}`);
  }
  if (entry.isDirectory() && !entry.name.startsWith("_")) {
    const definition = await readToolDefinition(cwd, directory, entry.name);
    if (definition) {
      const existing = definitions.findIndex(
        (item): boolean => item.id === definition.id
      );
      if (existing !== -1) {
        definitions.splice(existing, 1);
      }
      definitions.push(definition);
    }
  }
  await collectDefinitions(cwd, directory, entries, definitions, index + 1);
};
/* oxlint-enable typescript/strict-boolean-expressions */
/* oxlint-enable typescript/prefer-readonly-parameter-types */
/* oxlint-enable eslint/no-magic-numbers */
/* oxlint-enable eslint/max-params */
/* oxlint-enable eslint/max-statements */

/* oxlint-disable unicorn/no-null -- Null is an explicit SDK, serialized-data, or React absence sentinel; replacing it would change the contract. */
/* oxlint-disable typescript/prefer-readonly-parameter-types -- This parameter participates in the existing SDK or mutable state contract; recursively readonly types would change assignability or permitted updates. */
const missingPreviousRegistration = (
  previousTools: string | null,
  ids: Set<string>,
  entries: Awaited<ReturnType<typeof readdir>>
): string | null => {
  for (const match of previousTools?.matchAll(
    /from "\.\/(?<id>[a-z][a-z0-9-]*)\/tool"/gu
  ) ?? []) {
    const id = match.groups?.id;
    if (
      !ids.has(id ?? "") &&
      entries.some((entry): boolean => entry.name === id)
    ) {
      return id ?? "";
    }
  }
  return null;
};
/* oxlint-enable typescript/prefer-readonly-parameter-types */
/* oxlint-enable unicorn/no-null */

const validateExpected = (
  definitions: readonly ReadonlyInput<ToolDefinition>[],
  expected: readonly ReadonlyInput<ToolDefinition>[]
): void => {
  for (const requested of expected) {
    const installed = definitions.find(
      (item): boolean => item.id === requested.id
    );
    if (!installed || JSON.stringify(installed) !== JSON.stringify(requested)) {
      throw new Error(
        `Installed descriptor does not match requested tool ${requested.id}. Check the registry item's files and overwrite choices.`
      );
    }
  }
};

/* oxlint-disable eslint/no-magic-numbers -- These literals encode local protocol limits, indexing, or fixture expectations; keep them beside the operation whose units they describe. */
const validateSelections = (
  definitions: readonly ReadonlyInput<ToolDefinition>[]
): void => {
  for (const slot of selectionSlots) {
    if (definitions.filter((item): boolean => item.slot === slot).length > 1) {
      throw new Error(
        `Only one ${slot} tool can be selected. Remove the previous tool directory before syncing.`
      );
    }
  }
};
/* oxlint-enable eslint/no-magic-numbers */

/* oxlint-disable eslint/no-magic-numbers -- These literals encode local protocol limits, indexing, or fixture expectations; keep them beside the operation whose units they describe. */
const orderedProperties = (
  properties: readonly { readonly key: string; readonly value: string }[]
): string =>
  properties
    .toSorted((leftProperty, rightProperty) => {
      if (leftProperty.key === rightProperty.key) {
        return 0;
      }
      return leftProperty.key < rightProperty.key ? -1 : 1;
    })
    .map(({ key, value }): string => `  ${key}: ${value},`)
    .join("\n");
/* oxlint-enable eslint/no-magic-numbers */

/* oxlint-disable eslint/no-magic-numbers -- These literals encode local protocol limits, indexing, or fixture expectations; keep them beside the operation whose units they describe. */
const registrationImports = (
  entries: readonly {
    readonly id: string;
    readonly name: string;
    readonly alias: string;
  }[],
  file: "tool" | "renderer"
): string => {
  const groups = new Map<string, string[]>();
  for (const item of entries) {
    const names = groups.get(item.id) ?? [];
    names.push(`${item.name} as ${item.alias}`);
    groups.set(item.id, names);
  }
  return [...groups]
    .map(([id, names]: readonly [string, readonly string[]]): string =>
      names.length === 1
        ? `import { ${names[0]} } from "./${id}/${file}";`
        : `import {\n${names.map((name): string => `  ${name},`).join("\n")}\n} from "./${id}/${file}";`
    )
    .join("\n");
};
/* oxlint-enable eslint/no-magic-numbers */

/* oxlint-disable eslint/no-magic-numbers -- These literals encode local protocol limits, indexing, or fixture expectations; keep them beside the operation whose units they describe. */
/* oxlint-disable typescript/prefer-readonly-parameter-types -- This parameter participates in the existing SDK or mutable state contract; recursively readonly types would change assignability or permitted updates. */
/* oxlint-disable typescript/strict-boolean-expressions -- This value-producing condition preserves the current nullish/empty sentinel behavior; coercing it would change the returned value. */
const sourceFor = (
  registrations: Registration[]
): { providerBody: string; toolBody: string; uiBody: string } => {
  const renderers = registrations.filter((item) => item.rendererExport);
  const providers = registrations.filter((item): boolean => item.provider);
  const ordinary = registrations.filter((item): boolean => !item.workflow);
  return {
    providerBody: `import { defineToolSet } from "@/lib/eve/tool-types";\n${registrationImports(
      providers.map((item, registrationIndex) => ({
        alias: `tool${registrationIndex}`,
        id: item.id,
        name: item.toolExport,
      })),
      "tool"
    )}\n\nexport const providers = defineToolSet(${providers.length > 0 ? `{\n${orderedProperties(providers.map((item, registrationIndex) => ({ key: registrationKey(item), value: `tool${registrationIndex}` })))}\n}` : "{}"});\n`,
    toolBody: `import { defineToolSet } from "@/lib/eve/tool-types";\nimport { customTools } from "./custom-tools";\n${ordinary.some((item): boolean => item.provider) ? 'import { providers } from "./providers";\n' : ""}${registrationImports(
      ordinary
        .filter((item): boolean => !item.provider)
        .map((item) => ({
          alias: `tool${registrations.indexOf(item)}`,
          id: item.id,
          name: item.toolExport,
        })),
      "tool"
    )}\n\nconst installed = defineToolSet(${ordinary.length > 0 ? `{\n${orderedProperties(ordinary.map((item) => ({ key: registrationKey(item), value: item.provider ? `providers.${item.key}` : `tool${registrations.indexOf(item)}` })))}\n}` : "{}"});\nfor (const key of Object.keys(customTools)) {\n  if (Object.hasOwn(installed, key)${registrations.some((item) => item.workflow) ? ` || ${JSON.stringify(registrations.filter((item) => item.workflow).map((item): string => item.key))}.includes(key)` : ""}) {\n    throw new Error(\`Duplicate tool registration: \${key}\`);\n  }\n}\nexport const tools = { ...installed, ...customTools };\n`,
    uiBody: `import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";\nimport { customUi } from "./custom-ui";\n${registrationImports(
      renderers.flatMap((item, registrationIndex) =>
        typeof item.rendererExport === "string" && item.rendererExport !== ""
          ? [
              {
                alias: `renderer${registrationIndex}`,
                id: item.id,
                name: item.rendererExport,
              },
            ]
          : []
      ),
      "renderer"
    )}\n\nconst installed = ${renderers.length > 0 ? `{\n${orderedProperties(renderers.map((item, registrationIndex) => ({ key: JSON.stringify(`tool-${registrationKey(item)}`), value: `renderer${registrationIndex}` })))}\n}` : "{}"};\nfor (const key of Object.keys(customUi)) {\n  if (Object.hasOwn(installed, key)) {\n    throw new Error(\`Duplicate renderer registration: \${key}\`);\n  }\n}\nexport const ui = { ...installed, ...customUi } satisfies ToolRendererRegistry;\n`,
  };
};
/* oxlint-enable typescript/strict-boolean-expressions */
/* oxlint-enable typescript/prefer-readonly-parameter-types */
/* oxlint-enable eslint/no-magic-numbers */

/* oxlint-disable eslint/max-statements -- These statements express one ordered operation with shared validation and cleanup; preserve the existing sequencing. */
/* oxlint-disable eslint/no-magic-numbers -- These literals encode local protocol limits, indexing, or fixture expectations; keep them beside the operation whose units they describe. */
/* oxlint-disable typescript/strict-boolean-expressions -- This value-producing condition preserves the current nullish/empty sentinel behavior; coercing it would change the returned value. */
const validateToolDependencies = (
  definitions: readonly ReadonlyInput<ToolDefinition>[]
): void => {
  const availableKeys = new Set(
    registrationsFor(definitions).map(
      (item: ReadonlyInput<Registration>): string => registrationKey(item)
    )
  );
  for (const definition of definitions) {
    const missingTools = definition.requiresTools.filter(
      (name): boolean => !availableKeys.has(name)
    );
    if (missingTools.length > 0) {
      throw new Error(
        `${definition.id} requires installed tools: ${missingTools.join(", ")}`
      );
    }
  }
  const runners = definitions.filter((item) => item.documentRunExport);
  if (runners.length > 1) {
    throw new Error("Only one saved-document executor can be installed.");
  }
  const executor = definitions.find(
    (item): boolean => item.slot === "codeExecution"
  );
  if (
    registrationsFor(definitions).some(
      (item: ReadonlyInput<Registration>): boolean =>
        registrationKey(item) === "runCodeDocument"
    ) &&
    !executor?.codeExecutorExport
  ) {
    throw new Error(
      "Saved code execution requires a compatible codeExecution provider, such as vercel-code-execution."
    );
  }
};
/* oxlint-enable typescript/strict-boolean-expressions */
/* oxlint-enable eslint/no-magic-numbers */
/* oxlint-enable eslint/max-statements */

const toolRegistrationTargets = [
  "tools.ts",
  "ui.ts",
  "document-ui.ts",
  "installed-features.ts",
  "composer-tools.ts",
  "document-run.ts",
  "providers.ts",
  "code-executor.ts",
  "workflow-types.ts",
  "tool-availability.ts",
  "custom-tools.ts",
  "custom-ui.ts",
].map((file): string => `tools/chatjs/${file}`);

/* oxlint-disable eslint/max-statements -- These statements express one ordered operation with shared validation and cleanup; preserve the existing sequencing. */
/* oxlint-disable eslint/max-lines-per-function -- Keep the ordered validation, state transitions, and cleanup in one operation so their sequencing remains reviewable. */
/* oxlint-disable typescript/prefer-readonly-parameter-types -- This parameter participates in the existing SDK or mutable state contract; recursively readonly types would change assignability or permitted updates. */
const readInstalledTools = async (cwd: string): Promise<ToolDefinition[]> => {
  const directory = "tools/chatjs";
  await preflight(cwd, toolRegistrationTargets);
  const dir = pathModule.join(cwd, directory);
  const entries = await readdir(dir, { withFileTypes: true }).catch(
    (error: unknown) => {
      if (
        error instanceof Error &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        return [];
      }
      throw error;
    }
  );
  const toolsPath = pathModule.join(dir, "tools.ts");
  const uiPath = pathModule.join(dir, "ui.ts");
  const previousTools = await readOptional(toolsPath);
  const previousUi = await readOptional(uiPath);
  checkGenerated(previousTools, toolsPath);
  checkGenerated(previousUi, uiPath);
  await Promise.all(
    [
      "document-ui.ts",
      "installed-features.ts",
      "composer-tools.ts",
      "document-run.ts",
      "providers.ts",
      "code-executor.ts",
      "workflow-types.ts",
      "tool-availability.ts",
    ].map(async (file): Promise<void> => {
      checkGenerated(await readOptional(pathModule.join(dir, file)), file);
    })
  );
  const definitions: ToolDefinition[] = [];
  await collectDefinitions(cwd, directory, entries, definitions);
  const ids = new Set(definitions.map((item): string => item.id));
  const previousProviders = await readOptional(
    pathModule.join(dir, "providers.ts")
  );
  const previousWorkflows = await readOptional(
    pathModule.join(dir, "workflow-types.ts")
  );
  const missing = missingPreviousRegistration(
    `${previousTools ?? ""}\n${previousProviders ?? ""}\n${previousWorkflows ?? ""}`,
    ids,
    entries
  );
  if (typeof missing === "string" && missing !== "") {
    throw new Error(
      `Missing descriptor for previously registered tool: ${missing}. Restore chatjs.json before syncing.`
    );
  }
  return definitions.toSorted((leftDefinition, rightDefinition): number =>
    leftDefinition.id.localeCompare(rightDefinition.id)
  );
};
/* oxlint-enable typescript/prefer-readonly-parameter-types */
/* oxlint-enable eslint/max-lines-per-function */
/* oxlint-enable eslint/max-statements */

const validateToolInstallation = async (
  cwd: string,
  definitions: readonly ReadonlyInput<ToolDefinition>[]
): Promise<void> => {
  validateSelections(definitions);
  const documents = definitions.filter((item) => item.documentKind);
  if (
    new Set(documents.map((item) => item.documentKind)).size !==
    documents.length
  ) {
    throw new Error("Only one bundle per document kind can be installed.");
  }
  const keys = registrationsFor(definitions).map(
    (item: ReadonlyInput<Registration>): string => registrationKey(item)
  );
  if (new Set(keys).size !== keys.length) {
    throw new Error("Duplicate installed tool registration key.");
  }
  await validateCustomToolKeys(cwd, definitions);
  validateToolDependencies(definitions);
};

/* oxlint-disable eslint/max-statements -- These statements express one ordered operation with shared validation and cleanup; preserve the existing sequencing. */
/* oxlint-disable eslint/max-lines-per-function -- Keep the ordered validation, state transitions, and cleanup in one operation so their sequencing remains reviewable. */
/* oxlint-disable eslint/no-magic-numbers -- These literals encode local protocol limits, indexing, or fixture expectations; keep them beside the operation whose units they describe. */
/* oxlint-disable typescript/prefer-readonly-parameter-types -- This parameter participates in the existing SDK or mutable state contract; recursively readonly types would change assignability or permitted updates. */
/* oxlint-disable typescript/strict-boolean-expressions -- This value-producing condition preserves the current nullish/empty sentinel behavior; coercing it would change the returned value. */
const syncTools = async (
  cwd: string,
  options: {
    readonly checkOnly?: boolean;
    readonly expected?: readonly ReadonlyInput<ToolDefinition>[];
  } = {}
): Promise<ToolDefinition[]> => {
  const definitions = await readInstalledTools(cwd);
  validateExpected(definitions, options.expected ?? []);
  await validateToolInstallation(cwd, definitions);
  if (options.checkOnly === true) {
    return definitions;
  }
  const dir = pathModule.join(cwd, "tools/chatjs");
  const toolsPath = pathModule.join(dir, "tools.ts");
  const uiPath = pathModule.join(dir, "ui.ts");
  const documents = definitions.filter((item) => item.documentKind);
  const registrations = registrationsFor(definitions);
  const keys = registrations.map((item): string => registrationKey(item));
  const { providerBody, toolBody, uiBody } = sourceFor(registrations);
  await mkdir(dir, { recursive: true });
  const [customTools, customUi] = await Promise.all([
    readOptional(pathModule.join(dir, "custom-tools.ts")),
    readOptional(pathModule.join(dir, "custom-ui.ts")),
  ]);
  await Promise.all([
    ...(customTools === null
      ? [
          writeFile(
            pathModule.join(dir, "custom-tools.ts"),
            generatedRegistrationSource(
              'import { defineToolSet } from "@/lib/eve/tool-types";\n\nexport const customTools = defineToolSet({});\n'
            )
          ),
        ]
      : []),
    ...(customUi === null
      ? [
          writeFile(
            pathModule.join(dir, "custom-ui.ts"),
            generatedRegistrationSource(
              'import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";\n\nexport const customUi = {} satisfies Partial<ToolRendererRegistry>;\n'
            )
          ),
        ]
      : []),
  ]);
  await writeFile(
    pathModule.join(dir, "document-ui.ts"),
    generatedSource(
      `"use client";\n\nimport type { DocumentUiRegistry } from "@/lib/eve/document-ui";\n\n${documents.map((item, index): string => `import { documentUi as document${index} } from "./${item.id}/document";`).join("\n")}\n\nexport const documentUi: DocumentUiRegistry = {\n${documents.map((item, index): string => `  ${item.documentKind}: document${index},`).join("\n")}\n};\n`
    )
  );
  await writeFile(
    pathModule.join(dir, "installed-features.ts"),
    generatedSource(
      `export const installedToolNames: ReadonlySet<string> = new Set(${JSON.stringify(keys)});\nexport const installedDocumentKinds: ReadonlySet<string> = new Set([\n${documents.map((item): string => `  ${JSON.stringify(item.documentKind)},`).join("\n")}\n]);\n`
    )
  );
  const composerTools = registrations
    .filter((item) => item.composer)
    .toSorted((leftRegistration, rightRegistration): number =>
      leftRegistration.key.localeCompare(rightRegistration.key)
    );
  await writeFile(
    pathModule.join(dir, "composer-tools.ts"),
    generatedSource(
      `import type { LucideIcon } from "lucide-react";\n${composerTools.length > 0 ? `import { ${composerTools.map((item, index): string => `${item.composer?.icon} as Icon${index}`).join(", ")} } from "lucide-react";` : ""}\n\nexport const composerTools: Readonly<Record<string, { icon: LucideIcon; name: string; shortName: string } | undefined>> = ${composerTools.length > 0 ? `{\n${composerTools.map((item, index): string => `  ${JSON.stringify(item.key)}: { icon: Icon${index}, name: ${JSON.stringify(item.composer?.name)}, shortName: ${JSON.stringify(item.composer?.shortName)} },`).join("\n")}\n}` : "{}"};\n`
    )
  );
  const runner = definitions.find((item) => item.documentRunExport);
  await writeFile(
    pathModule.join(dir, "document-run.ts"),
    generatedSource(
      `"use client";\n\nimport type { ComponentType } from "react";\n\nimport type { DocumentRunProps } from "@/lib/eve/document-ui";\n${runner ? `\nimport { ${runner.documentRunExport} as InstalledDocumentRun } from "./${runner.id}/document";\n` : ""}\nexport const DocumentRun: ComponentType<DocumentRunProps> | undefined =\n  ${runner ? "InstalledDocumentRun" : "undefined"};\n`
    )
  );
  await writeFile(
    pathModule.join(dir, "providers.ts"),
    generatedSource(providerBody)
  );
  const executor = definitions.find((item) => item.codeExecutorExport);
  await writeFile(
    pathModule.join(dir, "code-executor.ts"),
    generatedSource(
      `import type { CodeExecutor } from "@/lib/eve/code-executor";\n${executor ? `import { ${executor.codeExecutorExport} as execute } from "./${executor.id}/tool";\n` : ""}\nexport const codeExecutor: CodeExecutor | undefined = ${executor ? "execute" : "undefined"};\n`
    )
  );
  const workflows = registrations.filter((item) => item.workflow);
  await writeFile(
    pathModule.join(dir, "workflow-types.ts"),
    generatedSource(
      `${workflows.map((item, registrationIndex): string => `import type { ${item.toolExport} as workflow${registrationIndex} } from "./${item.id}/tool";`).join("\n")}\n\nexport type WorkflowTools = {\n${workflows.map((item, registrationIndex): string => `  ${item.key}: typeof workflow${registrationIndex};`).join("\n")}\n};\n`
    )
  );
  const availability = definitions.filter((item) => item.availabilityExport);
  await writeFile(
    pathModule.join(dir, "tool-availability.ts"),
    generatedSource(
      `import type { ToolAvailability } from "@/lib/eve/tool-availability";\n${availability.map((item, registrationIndex): string => `import { ${item.availabilityExport} as available${registrationIndex} } from "./${item.id}/availability";`).join("\n")}\n\nexport const toolAvailability: Record<string, ToolAvailability> = {\n${availability.flatMap((item, registrationIndex) => item.tools.map((tool): string => `  ${item.slot ?? tool.toolExport}: available${registrationIndex},`)).join("\n")}\n};\n`
    )
  );
  await writeFile(toolsPath, generatedSource(toolBody));
  await writeFile(uiPath, generatedSource(uiBody));
  return definitions;
};
/* oxlint-enable typescript/strict-boolean-expressions */
/* oxlint-enable typescript/prefer-readonly-parameter-types */
/* oxlint-enable eslint/no-magic-numbers */
/* oxlint-enable eslint/max-lines-per-function */
/* oxlint-enable eslint/max-statements */

/* oxlint-disable max-lines -- Keep this cohesive contract and its cases together; splitting it solely for a line quota would obscure shared setup or state transitions. */
export {
  readInstalledTools,
  syncTools,
  toolRegistrationTargets,
  validateToolInstallation,
};
