import { afterEach, expect, test } from "bun:test";
// oxlint-disable-next-line import/no-nodejs-modules -- This Bun integration fixture reads, writes, and validates real project files with native filesystem APIs.
import {
  mkdtemp,
  mkdir,
  readFile,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
// oxlint-disable-next-line import/no-nodejs-modules -- The Bun test runtime provides temporary-directory and platform information for this filesystem operation.
import { tmpdir } from "node:os";
// oxlint-disable-next-line import/no-nodejs-modules -- This Bun integration fixture resolves platform-specific project and installation paths.
import path from "node:path";

import { syncTools } from "./sync-tools";

const roots: string[] = [];

/* oxlint-disable eslint/no-magic-numbers -- These values are concrete test inputs and expected results; naming each literal would make the fixture harder to compare with its assertions. */
/* oxlint-disable typescript/promise-function-async -- Return the existing promise directly to preserve its identity and the current synchronous-throw boundary. */
afterEach(async () => {
  await Promise.all(
    roots.splice(0).map((root) => rm(root, { force: true, recursive: true }))
  );
});
/* oxlint-enable typescript/promise-function-async */
/* oxlint-enable eslint/no-magic-numbers */
const project = async (): Promise<string> => {
  const root = await mkdtemp(path.join(tmpdir(), "chatjs-sync-"));
  roots.push(root);
  await mkdir(path.join(root, "lib/eve"), { recursive: true });
  await symlink(
    path.resolve(
      import.meta.dir,
      "../../../../apps/chat/lib/eve/tool-types.ts"
    ),
    path.join(root, "lib/eve/tool-types.ts")
  );
  await writeFile(
    path.join(root, "tsconfig.json"),
    JSON.stringify({ compilerOptions: { paths: { "@/*": ["./*"] } } })
  );
  await syncTools(root);
  return root;
};
const install = async (
  root: string,
  id = "word-count",
  toolExport = "wordCount"
): Promise<void> => {
  const dir = path.join(root, "tools/chatjs", id);
  await mkdir(dir, { recursive: true });
  const definition = {
    contractVersion: 1,
    envRequirements: [],
    id,
    kind: "tool",
    tools: [{ rendererExport: "WordCountRenderer", toolExport }],
  };
  await writeFile(path.join(dir, "chatjs.json"), JSON.stringify(definition));
  await writeFile(
    path.join(dir, "tool.ts"),
    `export const ${toolExport} = {};`
  );
  await writeFile(
    path.join(dir, "renderer.tsx"),
    "export const WordCountRenderer = () => null;"
  );
};
/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
test("sync registers direct installs deterministically and preserves custom modules", async () => {
  const root = await project();
  const emptyTools = await readFile(
    path.join(root, "tools/chatjs/tools.ts"),
    "utf-8"
  );
  expect(emptyTools).not.toContain("import { providers }");
  expect(emptyTools).toContain("const installed = defineToolSet({});");
  expect(
    await readFile(path.join(root, "tools/chatjs/providers.ts"), "utf-8")
  ).toContain("export const providers = defineToolSet({});");
  expect(
    await readFile(path.join(root, "tools/chatjs/ui.ts"), "utf-8")
  ).toContain("const installed = {};");
  await install(root);
  const custom = path.join(root, "tools/chatjs/custom-tools.ts");
  await writeFile(custom, "export const customTools = { custom: {} };\n");
  await syncTools(root);
  const before = await readFile(
    path.join(root, "tools/chatjs/tools.ts"),
    "utf-8"
  );
  expect(before).toContain('from "./word-count/tool"');
  expect(before).not.toContain("import { providers }");
  expect(before).toContain("Object.hasOwn");
  const installedBefore = await readFile(
    path.join(root, "tools/chatjs/installed-features.ts"),
    "utf-8"
  );
  const [header, contentHash, ...body] = installedBefore.split("\n");
  expect(header).toContain("Generated by chat-js sync");
  expect(contentHash).toBe(
    `// Content: ${new Bun.CryptoHasher("sha256").update(body.join("\n")).digest("hex")}`
  );
  expect(installedBefore).toContain(
    "export { installedToolNames, installedDocumentKinds };"
  );
  expect(installedBefore).not.toContain("import/group-exports");
  await syncTools(root);
  expect(
    await readFile(path.join(root, "tools/chatjs/tools.ts"), "utf-8")
  ).toBe(before);
  expect(
    await readFile(
      path.join(root, "tools/chatjs/installed-features.ts"),
      "utf-8"
    )
  ).toBe(installedBefore);
  expect(await readFile(custom, "utf-8")).toContain("custom: {}");
});
/* oxlint-enable eslint/max-statements */
/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
test("generated registries sort by registration key instead of directory name", async () => {
  const root = await project();
  await install(root, "a-tool", "zebra");
  await install(root, "z-tool", "alpha");
  await syncTools(root);
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { tools } = await import(path.join(root, "tools/chatjs/tools.ts"));
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { ui } = await import(path.join(root, "tools/chatjs/ui.ts"));
  // oxlint-disable-next-line typescript/no-unsafe-argument -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  expect(Object.keys(tools)).toEqual(["alpha", "zebra"]);
  // oxlint-disable-next-line typescript/no-unsafe-argument -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  expect(Object.keys(ui)).toEqual(["tool-alpha", "tool-zebra"]);
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { alpha } = await import(
    path.join(root, "tools/chatjs/z-tool/tool.ts")
  );
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { zebra } = await import(
    path.join(root, "tools/chatjs/a-tool/tool.ts")
  );
  // oxlint-disable-next-line typescript/no-unsafe-member-access -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  expect(tools.alpha).toBe(alpha);
  // oxlint-disable-next-line typescript/no-unsafe-member-access -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  expect(tools.zebra).toBe(zebra);
  await syncTools(root);
});
/* oxlint-enable eslint/max-statements */
test("missing descriptors and edited generated output fail without dropping registrations", async () => {
  const root = await project();
  await install(root);
  await syncTools(root);
  const index = path.join(root, "tools/chatjs/tools.ts");
  const before = await readFile(index, "utf-8");
  await rm(path.join(root, "tools/chatjs/word-count/chatjs.json"));
  expect(syncTools(root)).rejects.toThrow("Missing descriptor");
  expect(await readFile(index, "utf-8")).toBe(before);
  await writeFile(index, `${before}\n// custom edit`);
  expect(syncTools(root)).rejects.toThrow("custom or legacy");
});
test("duplicate keys and symlink directories fail before writing indexes", async () => {
  const root = await project();
  await install(root);
  await install(root, "other");
  expect(syncTools(root)).rejects.toThrow("Duplicate installed");
  await rm(path.join(root, "tools/chatjs/other"), { recursive: true });
  await symlink(
    path.join(root, "tools/chatjs/word-count"),
    path.join(root, "tools/chatjs/other")
  );
  expect(syncTools(root)).rejects.toThrow("symlinks");
});
test("a requested tool cannot report successful registration without its descriptor", async () => {
  const root = await project();
  expect(
    syncTools(root, {
      expected: [
        {
          contractVersion: 1,
          envRequirements: [],
          id: "missing",
          kind: "tool",
          requiresTools: [],
          tools: [{ rendererExport: "Missing", toolExport: "missing" }],
        },
      ],
    })
  ).rejects.toThrow("does not match requested");
});

const installSearch = async (
  root: string,
  id: string,
  key: string
): Promise<void> => {
  const dir = path.join(root, "tools/chatjs", id);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "tool.ts"), "export const webSearch = {};");
  await writeFile(
    path.join(dir, "chatjs.json"),
    JSON.stringify({
      contractVersion: 1,
      envRequirements: [{ options: [[key]] }],
      id,
      kind: "tool",
      slot: "webSearch",
      tools: [{ toolExport: "webSearch" }],
    })
  );
};
/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
/* oxlint-disable eslint/no-magic-numbers -- These values are concrete test inputs and expected results; naming each literal would make the fixture harder to compare with its assertions. */
test("search selections register standard tools without requiring a renderer", async () => {
  const root = await project();
  await installSearch(root, "external-search", "EXTERNAL_SEARCH_KEY");
  const definitions = await syncTools(root);
  expect(definitions[0]?.envRequirements).toEqual([
    { options: [["EXTERNAL_SEARCH_KEY"]] },
  ]);
  expect(
    await readFile(path.join(root, "tools/chatjs/providers.ts"), "utf-8")
  ).toContain("./external-search/tool");
  expect(
    readFile(path.join(root, "tools/chatjs/search-config.ts"), "utf-8")
  ).rejects.toMatchObject({ code: "ENOENT" });
  expect(
    await readFile(path.join(root, "tools/chatjs/tools.ts"), "utf-8")
  ).toContain("providers.webSearch");
  expect(
    await readFile(path.join(root, "tools/chatjs/ui.ts"), "utf-8")
  ).not.toContain("external-search");
  await installSearch(root, "another-search", "ANOTHER_KEY");
  expect(syncTools(root)).rejects.toThrow("Only one webSearch");
  await rm(path.join(root, "tools/chatjs/external-search"), {
    recursive: true,
  });
  await syncTools(root);
  expect(
    await readFile(path.join(root, "tools/chatjs/providers.ts"), "utf-8")
  ).not.toContain("external-search/tool");
});
/* oxlint-enable eslint/no-magic-numbers */
/* oxlint-enable eslint/max-statements */
const installExecution = async (root: string, id: string): Promise<void> => {
  const dir = path.join(root, "tools/chatjs", id);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, "tool.ts"), "export const runCode = {};");
  await writeFile(
    path.join(dir, "chatjs.json"),
    JSON.stringify({
      contractVersion: 1,
      envRequirements: [
        { options: [["RUNNER_TOKEN"], ["RUNNER_ID", "RUNNER_SECRET"]] },
        { options: [["RUNNER_REGION"]] },
      ],
      id,
      kind: "tool",
      slot: "codeExecution",
      tools: [{ toolExport: "runCode" }],
    })
  );
};
/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
test("external execution tools compose with search and reject duplicate providers", async () => {
  const root = await project();
  await installSearch(root, "external-search", "SEARCH_KEY");
  await installExecution(root, "external-runner");
  await syncTools(root);
  const selection = path.join(root, "tools/chatjs/providers.ts");
  const before = await readFile(selection, "utf-8");
  expect(before).toContain("runCode as tool");
  expect(before).toContain("codeExecution: tool");
  expect(
    await readFile(path.join(root, "tools/chatjs/providers.ts"), "utf-8")
  ).toContain("external-runner");
  expect(
    await readFile(path.join(root, "tools/chatjs/ui.ts"), "utf-8")
  ).not.toContain("external-runner");
  await installExecution(root, "second-runner");
  expect(syncTools(root)).rejects.toThrow("Only one codeExecution");
  expect(await readFile(selection, "utf-8")).toBe(before);
  await rm(path.join(root, "tools/chatjs/external-runner"), {
    recursive: true,
  });
  await rm(path.join(root, "tools/chatjs/second-runner"), { recursive: true });
  await syncTools(root);
  expect(await readFile(selection, "utf-8")).not.toContain("codeExecution:");
  await writeFile(selection, "// user code");
  expect(syncTools(root)).rejects.toThrow("custom or legacy");
});
/* oxlint-enable eslint/max-statements */

test("URL retrieval uses the selected export and rejects duplicate providers", async () => {
  const root = await project();
  const installRetrieval = async (id: string): Promise<void> => {
    const dir = path.join(root, "tools/chatjs", id);
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, "tool.ts"), "export const readPage = {};");
    await writeFile(
      path.join(dir, "chatjs.json"),
      JSON.stringify({
        contractVersion: 1,
        envRequirements: [{ options: [["PAGE_TOKEN"]] }],
        id,
        kind: "tool",
        slot: "retrieveUrl",
        tools: [{ toolExport: "readPage" }],
      })
    );
  };
  await installRetrieval("custom-retrieval");
  await syncTools(root);
  const server = await readFile(
    path.join(root, "tools/chatjs/providers.ts"),
    "utf-8"
  );
  expect(server).toContain("readPage as tool");
  expect(server).toContain("retrieveUrl: tool");
  await installRetrieval("second-retrieval");
  expect(syncTools(root)).rejects.toThrow("Only one retrieveUrl");
  expect(
    await readFile(path.join(root, "tools/chatjs/providers.ts"), "utf-8")
  ).toBe(server);
});

/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
test("tools register natively, retain renderers and cannot collide with custom tools", async () => {
  const root = await project();
  await install(root, "native-counter", "countWords");
  await syncTools(root);
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { tools } = await import(path.join(root, "tools/chatjs/tools.ts"));
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { ui } = await import(path.join(root, "tools/chatjs/ui.ts"));
  // oxlint-disable-next-line typescript/no-unsafe-argument -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  expect(Object.keys(tools)).toEqual(["countWords"]);
  // oxlint-disable-next-line typescript/no-unsafe-argument -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  expect(Object.keys(ui)).toEqual(["tool-countWords"]);
  await writeFile(
    path.join(root, "tools/chatjs/custom-tools.ts"),
    "export const customTools = { countWords: {} };\n"
  );
  const before = await readFile(
    path.join(root, "tools/chatjs/tools.ts"),
    "utf-8"
  );
  expect(syncTools(root)).rejects.toThrow("Custom tools conflict");
  expect(
    await readFile(path.join(root, "tools/chatjs/tools.ts"), "utf-8")
  ).toBe(before);
});
/* oxlint-enable eslint/max-statements */

/* oxlint-disable eslint/no-magic-numbers -- These values are concrete test inputs and expected results; naming each literal would make the fixture harder to compare with its assertions. */
test("sync preserves request-context auth and environment credential fallbacks", async () => {
  const root = await project();
  await installExecution(root, "vercel-runner");
  const descriptor = path.join(root, "tools/chatjs/vercel-runner/chatjs.json");
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const definition = JSON.parse(await readFile(descriptor, "utf-8"));
  // oxlint-disable-next-line typescript/no-unsafe-member-access -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  definition.envRequirements[0].runtimeAuth = "vercel-oidc";
  await writeFile(descriptor, JSON.stringify(definition));
  const definitions = await syncTools(root);
  expect(definitions[0]?.envRequirements).toEqual([
    {
      options: [["RUNNER_TOKEN"], ["RUNNER_ID", "RUNNER_SECRET"]],
      runtimeAuth: "vercel-oidc",
    },
    { options: [["RUNNER_REGION"]] },
  ]);
});
/* oxlint-enable eslint/no-magic-numbers */

/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
test("a bundle registers each native tool and renderer and rejects cross-bundle collisions", async () => {
  const root = await project();
  const dir = path.join(root, "tools/chatjs/text-documents");
  await mkdir(dir, { recursive: true });
  await writeFile(
    path.join(dir, "chatjs.json"),
    JSON.stringify({
      contractVersion: 1,
      id: "text-documents",
      kind: "tool",
      tools: [
        {
          rendererExport: "DocumentRenderer",
          toolExport: "createTextDocument",
        },
        { rendererExport: "DocumentRenderer", toolExport: "editTextDocument" },
      ],
    })
  );
  await writeFile(
    path.join(dir, "tool.ts"),
    "export const createTextDocument = {}; export const editTextDocument = {};"
  );
  await writeFile(
    path.join(dir, "renderer.tsx"),
    "export const DocumentRenderer = () => null;"
  );
  await syncTools(root);
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { tools } = await import(path.join(root, "tools/chatjs/tools.ts"));
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { ui } = await import(path.join(root, "tools/chatjs/ui.ts"));
  // oxlint-disable-next-line typescript/no-unsafe-argument -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  expect(Object.keys(tools)).toEqual([
    "createTextDocument",
    "editTextDocument",
  ]);
  // oxlint-disable-next-line typescript/no-unsafe-argument -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  expect(Object.keys(ui)).toEqual([
    "tool-createTextDocument",
    "tool-editTextDocument",
  ]);
  await install(root, "other", "editTextDocument");
  expect(syncTools(root)).rejects.toThrow("Duplicate installed");
});
/* oxlint-enable eslint/max-statements */

/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
test("sync rejects removing a dependency but permits uninstalling a complete bundle", async () => {
  const root = await project();
  await install(root, "read-document", "readDocument");
  await install(root, "text-documents", "createTextDocument");
  const descriptor = path.join(root, "tools/chatjs/text-documents/chatjs.json");
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const definition = JSON.parse(await readFile(descriptor, "utf-8"));
  // oxlint-disable-next-line typescript/no-unsafe-member-access -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  definition.requiresTools = ["readDocument"];
  await writeFile(descriptor, JSON.stringify(definition));
  await syncTools(root);
  const index = path.join(root, "tools/chatjs/tools.ts");
  const before = await readFile(index, "utf-8");
  await rm(path.join(root, "tools/chatjs/read-document"), { recursive: true });
  expect(syncTools(root)).rejects.toThrow(
    "requires installed tools: readDocument"
  );
  expect(syncTools(root, { checkOnly: true })).rejects.toThrow(
    "requires installed tools: readDocument"
  );
  expect(await readFile(index, "utf-8")).toBe(before);
  await rm(path.join(root, "tools/chatjs/text-documents"), { recursive: true });
  await syncTools(root);
  expect(await readFile(index, "utf-8")).not.toContain("createTextDocument");
});
/* oxlint-enable eslint/max-statements */

/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
test("saved-code registration requires an explicitly compatible executor", async () => {
  const root = await project();
  await installExecution(root, "external-runner");
  await install(root, "saved-code-execution", "runCodeDocument");
  expect(syncTools(root)).rejects.toThrow("compatible codeExecution provider");
  const descriptor = path.join(
    root,
    "tools/chatjs/external-runner/chatjs.json"
  );
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const definition = JSON.parse(await readFile(descriptor, "utf-8"));
  // oxlint-disable-next-line typescript/no-unsafe-member-access -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  definition.codeExecutorExport = "executeCode";
  // oxlint-disable-next-line typescript/no-unsafe-member-access -- Amend the parsed external descriptor fixture before validating it through sync.
  definition.codeExecutionCapabilities = {
    cancellation: "terminate",
    cleanup: "durable-allocation",
    files: "ephemeral",
    languages: ["python", "javascript"],
    timeout: "bounded",
    usage: "single-receipt",
  };
  await writeFile(descriptor, JSON.stringify(definition));
  await writeFile(
    path.join(root, "tools/chatjs/external-runner/tool.ts"),
    `import type { CodeExecutor } from "@/lib/eve/code-executor";
export const executeCode: CodeExecutor = async () => ({
  kind: "chatjs.tool-result",
  status: "success",
  version: 1,
  output: { chart: null, message: "executed" },
  usage: { costUsd: 0 },
});
export const runCode = {};`
  );
  await syncTools(root);
  const registration = await readFile(
    path.join(root, "tools/chatjs/code-executor.ts"),
    "utf-8"
  );
  expect(registration).toContain(
    'import { executeCode as execute } from "./external-runner/tool"'
  );
  expect(registration).toContain(
    "codeExecutor: CodeExecutor | undefined = execute"
  );
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const { codeExecutor } = await import(
    path.join(root, "tools/chatjs/code-executor.ts")
  );
  expect(typeof codeExecutor).toBe("function");
});
/* oxlint-enable eslint/max-statements */

/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
test.each([false, true])(
  "workflow installs stay static and reject custom collisions: %s",
  async (collision) => {
    const root = await project();
    const dir = path.join(root, "tools/chatjs/workflow");
    await mkdir(dir, { recursive: true });
    await writeFile(
      path.join(dir, "tool.ts"),
      'export { default as research } from "@/agent/tools/research";'
    );
    await writeFile(
      path.join(dir, "chatjs.json"),
      JSON.stringify({
        contractVersion: 1,
        id: "workflow",
        kind: "tool",
        tools: [{ toolExport: "research", workflow: true }],
      })
    );
    expect(syncTools(root)).rejects.toThrow();
    await mkdir(path.join(root, "agent/tools"), { recursive: true });
    await writeFile(
      path.join(root, "agent/tools/research.ts"),
      'export default { execute: () => "report" };'
    );
    await syncTools(root);
    if (collision) {
      await writeFile(
        path.join(root, "tools/chatjs/custom-tools.ts"),
        "export const customTools = { research: {} };\n"
      );
      expect(syncTools(root)).rejects.toThrow(
        "Custom tools conflict with installed tools: research"
      );
      return;
    }
    // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
    const { tools } = await import(path.join(root, "tools/chatjs/tools.ts"));
    // oxlint-disable-next-line typescript/no-unsafe-argument -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
    expect(Object.keys(tools)).toEqual([]);
    expect(
      await readFile(path.join(root, "tools/chatjs/workflow-types.ts"), "utf-8")
    ).toContain("research: typeof workflow0");
    await rm(path.join(dir, "chatjs.json"));
    expect(syncTools(root)).rejects.toThrow("Missing descriptor");
  }
);
/* oxlint-enable eslint/max-statements */

/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
/* oxlint-disable eslint/no-magic-numbers -- These values are concrete test inputs and expected results; naming each literal would make the fixture harder to compare with its assertions. */
test("composer metadata follows installation and removal without editing UI order", async () => {
  const root = await project();
  await install(root);
  const descriptor = path.join(root, "tools/chatjs/word-count/chatjs.json");
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const definition = JSON.parse(await readFile(descriptor, "utf-8"));
  // oxlint-disable-next-line typescript/no-unsafe-member-access -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  definition.tools[0].composer = {
    icon: "Hash",
    name: "Count words",
    shortName: "Words",
  };
  await writeFile(descriptor, JSON.stringify(definition));
  const order = path.join(root, "composer-controls.ts");
  await writeFile(order, "// Application-owned ordering\n");
  await syncTools(root);
  const generated = path.join(root, "tools/chatjs/composer-tools.ts");
  const before = await readFile(generated, "utf-8");
  expect(before).toContain('import { Hash as Icon0 } from "lucide-react"');
  expect(before).toContain(
    '"wordCount": { icon: Icon0, name: "Count words", shortName: "Words" }'
  );
  await syncTools(root);
  expect(await readFile(generated, "utf-8")).toBe(before);
  await rm(path.join(root, "tools/chatjs/word-count"), { recursive: true });
  await syncTools(root);
  expect(await readFile(generated, "utf-8")).not.toContain("wordCount");
  expect(await readFile(order, "utf-8")).toBe(
    "// Application-owned ordering\n"
  );
});
/* oxlint-enable eslint/no-magic-numbers */
/* oxlint-enable eslint/max-statements */

/* oxlint-disable eslint/max-statements -- Keep the test setup, action, and assertions together so this scenario remains independently understandable. */
/* oxlint-disable eslint/no-magic-numbers -- These values are concrete test inputs and expected results; naming each literal would make the fixture harder to compare with its assertions. */
test("invalid composer icon is rejected before generated files change", async () => {
  const root = await project();
  await install(root);
  await syncTools(root);
  const generated = path.join(root, "tools/chatjs/composer-tools.ts");
  const before = await readFile(generated, "utf-8");
  const descriptor = path.join(root, "tools/chatjs/word-count/chatjs.json");
  // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  const definition = JSON.parse(await readFile(descriptor, "utf-8"));
  // oxlint-disable-next-line typescript/no-unsafe-member-access -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
  definition.tools[0].composer = {
    icon: "NotALucideIcon",
    name: "Count words",
    shortName: "Words",
  };
  await writeFile(descriptor, JSON.stringify(definition));
  expect(syncTools(root)).rejects.toThrow("icon");
  expect(await readFile(generated, "utf-8")).toBe(before);
});
/* oxlint-enable eslint/no-magic-numbers */
/* oxlint-enable eslint/max-statements */

/* oxlint-disable eslint/no-magic-numbers -- These values are concrete test inputs and expected results; naming each literal would make the fixture harder to compare with its assertions. */
test.each(["GlobeIcon", "BookOpen", "Edit3"])(
  "composer icon validation accepts %s",
  async (icon) => {
    const root = await project();
    await install(root);
    const descriptor = path.join(root, "tools/chatjs/word-count/chatjs.json");
    // oxlint-disable-next-line typescript/no-unsafe-assignment -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
    const definition = JSON.parse(await readFile(descriptor, "utf-8"));
    // oxlint-disable-next-line typescript/no-unsafe-member-access -- Inspect the generated fixture output directly so shape or value regressions fail the runtime assertions below; parsing it into a new contract would change this test boundary.
    definition.tools[0].composer = {
      icon,
      name: "Count words",
      shortName: "Words",
    };
    await writeFile(descriptor, JSON.stringify(definition));
    await syncTools(root);
    expect(
      await readFile(path.join(root, "tools/chatjs/composer-tools.ts"), "utf-8")
    ).toContain(`${icon} as Icon0`);
  }
);

/* oxlint-disable max-lines -- Keep this cohesive contract and its cases together; splitting it solely for a line quota would obscure shared setup or state transitions. */
/* oxlint-enable eslint/no-magic-numbers */
