import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import ts from "typescript";

import { featureDefinitionSchema } from "../../../registry/metadata";
import { mcpFiles } from "../../../registry/src/features/mcp";

const exists = async (file: string) => {
  try {
    await access(file);
    return true;
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return false;
    }
    throw error;
  }
};

// UI files are application-owned. Only append the newly installed contribution;
// never recreate an existing array or change the user's ordering.
const appendContribution = async (
  file: string,
  name: string,
  entry: string,
  importLine: string,
  marker: string
) => {
  const source = await readFile(file, "utf-8");
  const parsed = ts.createSourceFile(
    file,
    source,
    ts.ScriptTarget.Latest,
    true
  );
  if (
    parsed.statements.some(
      (node) =>
        ts.isImportDeclaration(node) &&
        ts.isStringLiteral(node.moduleSpecifier) &&
        node.moduleSpecifier.text === marker
    )
  ) {
    return;
  }
  const declaration = parsed.statements
    .filter(ts.isVariableStatement)
    .flatMap((statement) => [...statement.declarationList.declarations])
    .find((item) => item.name.getText(parsed) === name);
  if (
    !declaration?.initializer ||
    !ts.isArrayLiteralExpression(declaration.initializer)
  ) {
    throw new Error(
      `Add the MCP contribution to ${file} manually: ${name} is no longer a literal array.`
    );
  }
  const array = declaration.initializer;
  const last = array.elements.at(-1);
  const importEnd =
    parsed.statements.findLast(
      (node) =>
        ts.isImportDeclaration(node) ||
        (ts.isExpressionStatement(node) && ts.isStringLiteral(node.expression))
    )?.end ?? 0;
  const edits = [
    { start: array.end - 1, text: `\n  ${entry},\n` },
    { start: importEnd, text: `\n${importLine}\n` },
  ];
  if (last && !array.elements.hasTrailingComma) {
    edits.push({ start: last.end, text: "," });
  }
  let content = source;
  for (const edit of edits.toSorted((a, b) => b.start - a.start)) {
    content =
      content.slice(0, edit.start) + edit.text + content.slice(edit.start);
  }
  await writeFile(file, content);
};

export const syncFeatures = async (
  cwd: string,
  options: { addUi?: boolean; expectedMcp?: boolean } = {}
) => {
  const descriptor = path.join(cwd, "features/mcp/chatjs.json");
  const mcp = await exists(descriptor);
  if (options.expectedMcp && !mcp) {
    throw new Error("MCP installation is missing features/mcp/chatjs.json.");
  }
  if (mcp) {
    featureDefinitionSchema.parse(
      JSON.parse(await readFile(descriptor, "utf-8"))
    );
    for (const file of mcpFiles) {
      // oxlint-disable-next-line eslint/no-await-in-loop -- Validate before writing registrations.
      await access(path.join(cwd, file));
    }
  }
  await mkdir(path.join(cwd, "features"), { recursive: true });
  await writeFile(
    path.join(cwd, "features/installed-routers.ts"),
    `// Generated by chat-js sync.\n${mcp ? 'import { mcpRouter } from "@/trpc/routers/mcp.router";\n\n' : ""}export const installedRouters = {${mcp ? " mcp: mcpRouter " : ""}};\n`
  );
  await writeFile(
    path.join(cwd, "features/installed.ts"),
    `// Generated by chat-js sync.\nexport const installedFeatures: ReadonlySet<string> = new Set(${JSON.stringify(mcp ? ["mcp"] : [])});\n`
  );
  if (mcp && options.addUi) {
    await appendContribution(
      path.join(cwd, "composer-controls.ts"),
      "composerControls",
      '{ Component: ConnectorsControl, id: "mcp" }',
      'import { ConnectorsControl } from "@/features/mcp/composer";',
      "@/features/mcp/composer"
    );
    await appendContribution(
      path.join(cwd, "settings-items.ts"),
      "settingsItems",
      "mcpSettingsItem",
      'import { mcpSettingsItem } from "@/features/mcp/settings";',
      "@/features/mcp/settings"
    );
  }
};

// Only fresh scaffolds use defaults. Cloning and sync never call this function.
export const initializeFeatureUi = async (cwd: string) => {
  for (const [file, name, marker, symbol] of [
    [
      "composer-controls.ts",
      "composerControls",
      "@/features/mcp/composer",
      "ConnectorsControl",
    ],
    [
      "settings-items.ts",
      "settingsItems",
      "@/features/mcp/settings",
      "mcpSettingsItem",
    ],
  ] as const) {
    const location = path.join(cwd, file);
    // oxlint-disable-next-line eslint/no-await-in-loop -- Only new scaffolds initialize these app-owned files.
    const source = await readFile(location, "utf-8");
    const parsed = ts.createSourceFile(
      file,
      source,
      ts.ScriptTarget.Latest,
      true
    );
    const edits: { start: number; end: number; text: string }[] = [];
    for (const node of parsed.statements) {
      if (
        ts.isImportDeclaration(node) &&
        ts.isStringLiteral(node.moduleSpecifier) &&
        node.moduleSpecifier.text === marker
      ) {
        edits.push({ end: node.end, start: node.getFullStart(), text: "" });
      }
      if (!ts.isVariableStatement(node)) {
        continue;
      }
      for (const declaration of node.declarationList.declarations) {
        if (
          declaration.name.getText(parsed) !== name ||
          !declaration.initializer ||
          !ts.isArrayLiteralExpression(declaration.initializer)
        ) {
          continue;
        }
        const array = declaration.initializer;
        const entries = array.elements.filter((entry) => {
          if (ts.isIdentifier(entry)) {
            return entry.text !== symbol;
          }
          return (
            !ts.isObjectLiteralExpression(entry) ||
            !entry.properties.some(
              (prop) =>
                ts.isPropertyAssignment(prop) &&
                ts.isIdentifier(prop.initializer) &&
                prop.initializer.text === symbol
            )
          );
        });
        edits.push({
          end: array.end,
          start: array.getStart(parsed),
          text: `[\n${entries.map((entry) => `${entry.getText(parsed)},`).join("\n")}\n]`,
        });
      }
    }
    let content = source;
    for (const edit of edits.toSorted((a, b) => b.start - a.start)) {
      content =
        content.slice(0, edit.start) + edit.text + content.slice(edit.end);
    }
    // oxlint-disable-next-line eslint/no-await-in-loop -- See above.
    await writeFile(location, content);
  }
  await syncFeatures(cwd);
};
