import { access, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { featureDefinitionSchema } from "../../../registry/metadata";
import { observabilityItems } from "../../../registry/src/features/observability";

const exists = async (file: string) => {
  try {
    await access(file);
    return true;
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return false;
    }
    throw error;
  }
};

// Validate every installed implementation before sync writes any registrations.
export const planObservability = async (cwd: string) => {
  const installed = await Promise.all(
    observabilityItems.map(async (item) => {
      const descriptor = path.join(cwd, `features/${item.name}/chatjs.json`);
      const present = await exists(descriptor);
      const files = await Promise.all(
        (item.files ?? []).map(async (file) => {
          const target = file.target?.replace(/^~\//u, "");
          if (!target) {
            throw new Error(
              `Observability file needs an explicit target: ${file.path}`
            );
          }
          return { present: await exists(path.join(cwd, target)), target };
        })
      );
      if (!present) {
        if (files.some((file) => file.present)) {
          throw new Error(
            `${item.name} is missing its descriptor. Run chat-js add ${item.name} to complete installation.`
          );
        }
        return null;
      }
      const definition = featureDefinitionSchema.parse(
        JSON.parse(await readFile(descriptor, "utf-8"))
      );
      if (definition.id !== item.name) {
        throw new Error(
          `Feature descriptor id must match its directory: ${item.name}`
        );
      }
      const missing = files.filter((file) => !file.present);
      if (missing.length > 0) {
        throw new Error(
          `${item.name} installation is incomplete. Missing: ${missing.map((file) => file.target).join(", ")}. Run chat-js add ${item.name}.`
        );
      }
      return item.name;
    })
  );
  const ids = installed.filter((id) => id !== null);
  const layout = ids.filter((id) => id !== "langfuse");
  const imports = layout
    .map(
      (id, index) =>
        `import { Component as Component${index} } from "@/features/${id}/component";`
    )
    .join("\n");
  const instrumentationImport = ids.includes("langfuse")
    ? 'import { register } from "@/features/langfuse/instrumentation";\n'
    : "";
  return {
    files: [
      {
        content: `// Generated by chat-js sync.\n${imports ? `${imports}\n` : ""}import type { InstalledLayoutComponent } from "@/lib/installation-contracts";\n\nexport const installedLayoutComponents: readonly {\n  id: string;\n  Component: InstalledLayoutComponent;\n}[] = ${layout.length > 0 ? `[\n${layout.map((id, index) => `  { Component: Component${index}, id: "${id}" },`).join("\n")}\n]` : "[]"};\n`,
        file: path.join(cwd, "features/installed-layout.ts"),
      },
      {
        content: `// Generated by chat-js sync.\n${instrumentationImport}import type { InstrumentationRegistration } from "@/lib/installation-contracts";\n\nexport const installedInstrumentation: readonly InstrumentationRegistration[] =\n  [${ids.includes("langfuse") ? "register" : ""}];\n`,
        file: path.join(cwd, "features/installed-instrumentation.ts"),
      },
    ],
    ids,
  };
};

// Creation only: reset demo selections. Sync/add never remove implementations.
export const initializeObservability = async (cwd: string) => {
  await Promise.all(
    observabilityItems.map((item) =>
      rm(path.join(cwd, "features", item.name), {
        force: true,
        recursive: true,
      })
    )
  );
  const manifestPath = path.join(cwd, "package.json");
  if (!(await exists(manifestPath))) {
    return;
  }
  const manifest = JSON.parse(await readFile(manifestPath, "utf-8"));
  for (const dependency of [
    "@vercel/analytics",
    "@vercel/speed-insights",
    "@vercel/otel",
    "langfuse-vercel",
    "langfuse",
  ]) {
    delete manifest.dependencies?.[dependency];
  }
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
};
