import { createHash } from "node:crypto";
import fs, {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { format } from "oxfmt";
import ultracite from "ultracite/oxfmt";
import { z } from "zod";

import { configureGatewayProvider } from "../../cli/src/helpers/gateway-provider";
import { configureStorageProvider } from "../../cli/src/helpers/storage-provider";
import { resolveGateway } from "../../cli/src/registry/gateways";
import { installItems } from "../../cli/src/registry/shadcn";
import { resolveStorage } from "../../cli/src/registry/storage";
import { planInstallation } from "../../cli/src/utils/installation-plan";
import { preflight } from "../../cli/src/utils/preflight";
import { syncFeatures } from "../../cli/src/utils/sync-features";
import { syncTools } from "../../cli/src/utils/sync-tools";
import { demoInstallation } from "../installation";
import { registry } from "../registry";

// Explicit demo exceptions, scoped to one value/import. Everything else is checked.
export const demoSource = (file: string, source: string) => {
  if (file === "lib/ai/gateway-model-defaults.ts") {
    // Keep the demo's existing chat model rather than the fresh scaffold default.
    return source.replace(
      'chat: "openai/gpt-5-mini"',
      'chat: "google/gemini-2.5-flash-lite"'
    );
  }
  return source;
};

const registryRoot = path.resolve(import.meta.dir, "..");
export const demoRoot = path.resolve(registryRoot, "../../apps/chat");
export const baselinePath = path.join(registryRoot, "demo-baseline.json");

const formatted = async (file: string, content: string) => {
  if (
    content.startsWith("// Generated by chat-js sync.") &&
    content.includes("\n// Content:")
  ) {
    return content;
  }
  const result = await format(file, content, ultracite);
  if (result.errors.length) {
    throw new Error(`Could not format demo source: ${file}`);
  }
  return result.code;
};
const digest = (content: string) =>
  createHash("sha256").update(content).digest("hex");
const optionalRead = async (file: string) => {
  try {
    return await readFile(file, "utf-8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return null;
    }
    throw error;
  }
};

const filesBelow = async (
  directory: string,
  prefix = ""
): Promise<string[]> => {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map((entry) => {
      const file = path.posix.join(prefix, entry.name);
      return entry.isDirectory()
        ? filesBelow(path.join(directory, entry.name), file)
        : [file];
    })
  );
  return nested.flat();
};

/** Install canonical sources through the CLI's planner and shadcn transforms. */
export const generateDemo = async (): Promise<Map<string, string>> => {
  const temporary = await mkdtemp(path.join(tmpdir(), "chatjs-demo-"));
  // This source-only registry retains registry dependencies, but omits package
  // installation: the demo already owns its workspace dependency manifest.
  const items = await Promise.all(
    registry.items.map(async (item) => {
      const files = await Promise.all(
        (item.files ?? []).map(async (file) => ({
          ...file,
          content: await readFile(path.join(registryRoot, file.path), "utf-8"),
        }))
      );
      const metadata = item.meta?.chatjs;
      if (metadata?.kind === "tool" || metadata?.kind === "feature") {
        const target =
          metadata.kind === "tool"
            ? `~/tools/chatjs/${item.name}/chatjs.json`
            : `~/features/${item.name}/chatjs.json`;
        files.push({
          content: await formatted(target, JSON.stringify(metadata)),
          path: `${item.name}.json`,
          target,
          type: "registry:file",
        });
      }
      return { ...item, dependencies: [], devDependencies: [], files };
    })
  );
  const server = Bun.serve({
    fetch(request) {
      const name = new URL(request.url).pathname
        .slice(1)
        .replace(/\.json$/u, "");
      const item = items.find((candidate) => candidate.name === name);
      return item
        ? Response.json(item)
        : new Response("Not found", { status: 404 });
    },
    hostname: "127.0.0.1",
    port: 0,
  });
  try {
    const components = JSON.parse(
      await readFile(path.join(demoRoot, "components.json"), "utf-8")
    );
    components.registries = {
      "@chatjs": `http://127.0.0.1:${server.port}/{name}.json`,
    };
    await mkdir(path.join(temporary, "app"), { recursive: true });
    await Promise.all([
      writeFile(
        path.join(temporary, "components.json"),
        JSON.stringify(components)
      ),
      writeFile(
        path.join(temporary, "package.json"),
        '{"name":"demo-sync","dependencies":{}}'
      ),
      writeFile(
        path.join(temporary, "tsconfig.json"),
        '{"compilerOptions":{"baseUrl":".","paths":{"@/*":["./*"]}}}'
      ),
      writeFile(
        path.join(temporary, "app/globals.css"),
        '@import "tailwindcss";'
      ),
    ]);
    const { gateway, storage } = demoInstallation;
    if (!gateway || !storage) {
      throw new Error("Demo preset requires gateway and storage selections");
    }
    const plan = await planInstallation(temporary, demoInstallation, {
      fresh: true,
    });
    await installItems(plan.sources, temporary, true);
    await configureGatewayProvider(
      temporary,
      await resolveGateway(gateway, temporary)
    );
    await configureStorageProvider(temporary, {
      ...(await resolveStorage(storage.source, temporary)),
      options: storage.options,
    });
    await syncTools(temporary, { expected: plan.expected });
    // Composer/settings ordering is application-owned; never initialize or add UI here.
    await syncFeatures(temporary, {
      expectedMcp: plan.features.some((feature) => feature.id === "mcp"),
      expectedUploads: plan.features.some(
        (feature) => feature.id === "attachment-uploads"
      ),
    });
    // Narrow application-owned exceptions: model catalog is fetched separately;
    // credentials, dependency manifests, UI order and extension files stay local.
    const excluded = new Set([
      "components.json",
      "composer-controls.ts",
      "settings-items.ts",
      "package.json",
      "tsconfig.json",
      "app/globals.css",
      ".env.example",
      "lib/ai/models.generated.ts",
      "tools/chatjs/custom-tools.ts",
      "tools/chatjs/custom-ui.ts",
    ]);
    const installedFiles = await filesBelow(temporary);
    const copies = await Promise.all(
      installedFiles
        .filter((file) => !excluded.has(file))
        .toSorted()
        .map(async (file) => {
          const content = await readFile(path.join(temporary, file), "utf-8");
          const normalized = await formatted(file, content);
          return [
            file,
            await formatted(file, demoSource(file, normalized)),
          ] as const;
        })
    );
    const output = new Map(copies);
    return output;
  } finally {
    server.stop(true);
    await rm(temporary, { force: true, recursive: true });
  }
};

const baselineSchema = z.strictObject({
  files: z.record(z.string(), z.string().regex(/^[a-f0-9]{64}$/u)),
  version: z.literal(1),
});

/** Stage every write before replacing files; retain originals until the baseline commits. */
const replaceDemoFiles = async (
  updates: { target: string; content: string; exists: boolean }[]
) => {
  const staged: {
    target: string;
    directory: string;
    exists: boolean;
    backedUp: boolean;
    installed: boolean;
  }[] = [];
  let retainBackups = false;
  try {
    for (const update of updates) {
      // oxlint-disable-next-line eslint/no-await-in-loop -- Stage all outputs before replacing any destination.
      await mkdir(path.dirname(update.target), { recursive: true });
      // oxlint-disable-next-line eslint/no-await-in-loop -- Temporary files must share the destination filesystem.
      const directory = await mkdtemp(
        path.join(path.dirname(update.target), ".demo-sync-")
      );
      staged.push({ ...update, backedUp: false, directory, installed: false });
      // oxlint-disable-next-line eslint/no-await-in-loop -- See above.
      await writeFile(path.join(directory, "next"), update.content);
    }
    for (const update of staged) {
      if (update.exists) {
        // oxlint-disable-next-line eslint/no-await-in-loop -- Keep originals for rollback until all replacements succeed.
        await fs.rename(update.target, path.join(update.directory, "previous"));
        update.backedUp = true;
      }
      // oxlint-disable-next-line eslint/no-await-in-loop -- Commit in order, with the baseline last.
      await fs.rename(path.join(update.directory, "next"), update.target);
      update.installed = true;
    }
  } catch (error) {
    const failures: unknown[] = [];
    for (const update of staged.toReversed()) {
      try {
        if (update.installed) {
          // oxlint-disable-next-line eslint/no-await-in-loop -- Restore replacements in reverse commit order.
          await rm(update.target);
        }
        if (update.backedUp) {
          // oxlint-disable-next-line eslint/no-await-in-loop -- See above.
          await fs.rename(
            path.join(update.directory, "previous"),
            update.target
          );
        }
      } catch (rollbackError) {
        failures.push(rollbackError);
      }
    }
    if (failures.length) {
      retainBackups = true;
      throw new AggregateError(
        [error, ...failures],
        `Demo sync rollback failed; recovery files retained in:\n${staged.map((update) => update.directory).join("\n")}`,
        { cause: error }
      );
    }
    throw error;
  } finally {
    if (!retainBackups) {
      await Promise.all(
        staged.map((update) =>
          rm(update.directory, { force: true, recursive: true })
        )
      );
    }
  }
};

/** Check all files before writing any: a failed protection check never partially syncs. */
export const syncDemo = async (options: {
  root: string;
  baseline: string;
  expected: Map<string, string>;
  check?: boolean;
  discard?: boolean;
}) => {
  const { root, baseline, expected, check = false, discard = false } = options;
  await preflight(path.dirname(baseline), [path.basename(baseline)]);
  const previous = await optionalRead(baseline);
  const record = previous ? baselineSchema.parse(JSON.parse(previous)) : null;
  const files = [
    ...new Set([...expected.keys(), ...Object.keys(record?.files ?? {})]),
  ].toSorted();
  await preflight(root, files);
  const current = new Map(
    await Promise.all(
      files.map(
        async (file) =>
          [file, await optionalRead(path.join(root, file))] as const
      )
    )
  );
  const edited = files.filter((file) => {
    const content = current.get(file) ?? null;
    // Edits moved upstream already match canonical output and can be adopted.
    if (content !== null && content === expected.get(file)) {
      return false;
    }
    const hash = content === null ? null : digest(content);
    return record?.files[file]
      ? hash !== record.files[file]
      : content !== null && content !== expected.get(file);
  });
  if (edited.length && !discard) {
    throw new Error(
      `Edited registry-owned demo files:\n${edited.join("\n")}\nMove changes upstream or explicitly regenerate with bun demo:sync --discard.`
    );
  }
  const staleOwnership = files.filter((file) => !expected.has(file));
  if (staleOwnership.length) {
    throw new Error(
      `Preset removed owned files; removal is outside demo sync scope:\n${staleOwnership.join("\n")}`
    );
  }
  const drift = files.filter(
    (file) => current.get(file) !== expected.get(file)
  );
  const next = {
    files: Object.fromEntries(
      files.map((file) => [file, digest(expected.get(file) ?? "")])
    ),
    version: 1,
  };
  const baselineContent = await formatted(
    "demo-baseline.json",
    JSON.stringify(next)
  );
  const baselineDrift = previous !== baselineContent;
  if (check) {
    if (drift.length || baselineDrift) {
      throw new Error(
        `Demo source drift:\n${drift.join("\n")}${baselineDrift ? `\nBaseline drift: ${baseline}` : ""}\nRun bun demo:sync to update source and its baseline.`
      );
    }
    return;
  }
  await replaceDemoFiles([
    ...drift.map((file) => ({
      content: expected.get(file) ?? "",
      exists: current.get(file) !== null,
      target: path.join(root, file),
    })),
    { content: baselineContent, exists: previous !== null, target: baseline },
  ]);
};

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (
    args.some((arg) => arg !== "--check" && arg !== "--discard") ||
    (args.includes("--check") && args.includes("--discard"))
  ) {
    throw new Error("Usage: bun demo:sync [--discard] | bun demo:check");
  }
  await syncDemo({
    baseline: baselinePath,
    check: args.includes("--check"),
    discard: args.includes("--discard"),
    expected: await generateDemo(),
    root: demoRoot,
  });
}
