/// <reference lib="es2023" />
/// <reference types="node" />
/* oxlint-disable import/no-namespace -- Enumerate Lucide runtime component exports, including documented aliases outside lucide.icons, to generate the complete composer catalog verified by the parity test. */
import * as lucide from "lucide-react";
/* oxlint-enable import/no-namespace */
/* oxlint-disable import/no-nodejs-modules -- This code runs on the Node/Bun server or installer and requires the built-in operating-system API. */
import { writeFile } from "node:fs/promises";
/* oxlint-enable import/no-nodejs-modules */

const components = new Set<unknown>(Object.values(lucide.icons));
const names = Object.entries(lucide)
  .filter(([, value]: readonly [string, unknown]) => components.has(value))
  .map(([name]: readonly [string, unknown]) => name)
  .toSorted();
// oxlint-disable-next-line node/no-top-level-await -- This Bun build executable finishes writing the generated icon inventory before the registry build starts.
await writeFile(
  new URL("../composer-icons.generated.ts", import.meta.url),
  `// Generated by bun scripts/generate-composer-icons.ts. Do not edit.\nexport const composerIconNames: ReadonlySet<string> = new Set(${JSON.stringify(names)});\n`
);
