import { writeFile } from "node:fs/promises";

import * as lucide from "lucide-react";

const components = new Set<unknown>(Object.values(lucide.icons));
const names = Object.entries(lucide)
  .filter(([, value]) => components.has(value))
  .map(([name]) => name)
  .toSorted();
await writeFile(
  new URL("../composer-icons.generated.ts", import.meta.url),
  `// Generated by bun scripts/generate-composer-icons.ts. Do not edit.\nexport const composerIconNames: ReadonlySet<string> = new Set(${JSON.stringify(names)});\n`
);
