// Generated by chat-js sync.
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { register } from "@/features/langfuse/instrumentation";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import type { InstrumentationRegistration } from "@/lib/installation-contracts";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const installedInstrumentation: readonly InstrumentationRegistration[] =
  [register];
