// Generated by chat-js sync.
// oxlint-disable-next-line import/no-named-export, import/prefer-default-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export { attachmentUploads } from "@/features/attachment-uploads/integration";
