// Generated by chat-js sync.
import { Component as Component0 } from "@/features/vercel-analytics/component";
import { Component as Component1 } from "@/features/vercel-speed-insights/component";
import type { InstalledLayoutComponent } from "@/lib/installation-contracts";

export const installedLayoutComponents: readonly {
  id: string;
  Component: InstalledLayoutComponent;
}[] = [
  { Component: Component0, id: "vercel-analytics" },
  { Component: Component1, id: "vercel-speed-insights" },
];
