// Generated by chat-js sync.
// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export { attachmentUploads } from "@/features/attachment-uploads/integration";
