// Generated by chat-js sync.
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { Component as Component0 } from "@/features/vercel-analytics/component";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { Component as Component1 } from "@/features/vercel-speed-insights/component";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import type { InstalledLayoutComponent } from "@/lib/installation-contracts";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const installedLayoutComponents: readonly {
  id: string;
  Component: InstalledLayoutComponent;
}[] = [
  { Component: Component0, id: "vercel-analytics" },
  { Component: Component1, id: "vercel-speed-insights" },
];
