// Generated by chat-js sync.
import { register } from "@/features/langfuse/instrumentation";
// oxlint-disable-next-line sort-imports -- Oxfmt places the runtime feature import before the erased registration type; preserve the formatter-owned generated import grouping.
import type { InstrumentationRegistration } from "@/lib/installation-contracts";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export -- Generated registrations expose separate named contracts and optional capabilities selected by the installer.
export const installedInstrumentation: readonly InstrumentationRegistration[] =
  [register];
