// Generated by chat-js sync.
import type { InstalledRouters } from "@/lib/installation-contracts";
import { mcpRouter } from "@/trpc/routers/mcp.router";

export const installedRouters = { mcp: mcpRouter } satisfies InstalledRouters;
