// Generated by chat-js sync.
import { register } from "@/features/langfuse/instrumentation";
import type { InstrumentationRegistration } from "@/lib/installation-contracts";

export const installedInstrumentation: readonly InstrumentationRegistration[] =
  [register];
