// Generated by chat-js sync.
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import type { InstalledRouters } from "@/lib/installation-contracts";
// oxlint-disable-next-line sort-imports -- Generated imports enumerate every installed registration in deterministic order.
import { mcpRouter } from "@/trpc/routers/mcp.router";

// oxlint-disable-next-line import/no-named-export, import/prefer-default-export, import/group-exports -- Generated named registrations preserve the app import contract, optional capabilities, and immutable custom overrides.
export const installedRouters = { mcp: mcpRouter } satisfies InstalledRouters;
