import type { OxlintConfig } from "oxlint";

// Audited restrictions are enforced repository-wide and in generated apps.
// Contract-specific exceptions belong beside the affected source code.
// oxlint-disable-next-line import/no-named-export, import/prefer-default-export -- Root and standalone configurations share this explicit named rule-map contract.
export const auditedRestrictionRules = {
  "id-length": "error",
  "import/exports-last": "error",
  "import/group-exports": "error",
  "import/max-dependencies": "error",
  "import/no-default-export": "error",
  "import/no-named-export": "error",
  "import/no-namespace": "error",
  "import/no-nodejs-modules": "error",
  "import/no-relative-parent-imports": "error",
  "import/prefer-default-export": "error",
  "init-declarations": "error",
  "jsdoc/require-param": "error",
  "jsdoc/require-returns": "error",
  "max-lines": ["error", { skipComments: true }],
  "max-lines-per-function": ["error", { skipComments: true }],
  "max-params": "error",
  "max-statements": "error",
  "no-console": "error",
  "no-continue": "error",
  "no-magic-numbers": "error",
  "no-ternary": "error",
  "no-undefined": "error",
  "no-underscore-dangle": "error",
  "node/no-process-env": "error",
  "node/no-sync": "error",
  "node/no-top-level-await": "error",
  "oxc/no-async-await": "error",
  "oxc/no-optional-chaining": "error",
  "oxc/no-rest-spread-properties": "error",
  "react-perf/jsx-no-jsx-as-prop": "error",
  "react-perf/jsx-no-new-array-as-prop": "error",
  "react-perf/jsx-no-new-function-as-prop": "error",
  "react-perf/jsx-no-new-object-as-prop": "error",
  "react/forbid-component-props": "error",
  "react/jsx-max-depth": "error",
  "react/jsx-no-literals": "error",
  "react/jsx-props-no-spreading": "error",
  "react/no-multi-comp": "error",
  "react/only-export-components": "error",
  "react/react-in-jsx-scope": "error",
  "sort-imports": "error",
  "typescript/consistent-type-definitions": "error",
  "typescript/explicit-function-return-type": "error",
  "typescript/explicit-module-boundary-types": "error",
  "typescript/prefer-readonly-parameter-types": "error",
  "typescript/promise-function-async": "error",
  "typescript/strict-boolean-expressions": "error",
  "typescript/strict-void-return": "error",
  "unicorn/max-nested-calls": "error",
  "unicorn/no-null": "error",
} satisfies NonNullable<OxlintConfig["rules"]>;
